/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AggregateConfiguration
 */
export interface AggregateConfiguration {
    /**
     * 
     * @type {boolean}
     * @memberof AggregateConfiguration
     */
    UseServerCapabilitiesDefaults?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AggregateConfiguration
     */
    TreatUncertainAsBad?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AggregateConfiguration
     */
    PercentDataBad?: number;
    /**
     * 
     * @type {number}
     * @memberof AggregateConfiguration
     */
    PercentDataGood?: number;
    /**
     * 
     * @type {boolean}
     * @memberof AggregateConfiguration
     */
    UseSlopedExtrapolation?: boolean;
}

/**
 * Check if a given object implements the AggregateConfiguration interface.
 */
export function instanceOfAggregateConfiguration(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AggregateConfigurationFromJSON(json: any): AggregateConfiguration {
    return AggregateConfigurationFromJSONTyped(json, false);
}

export function AggregateConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AggregateConfiguration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'UseServerCapabilitiesDefaults': !exists(json, 'UseServerCapabilitiesDefaults') ? undefined : json['UseServerCapabilitiesDefaults'],
        'TreatUncertainAsBad': !exists(json, 'TreatUncertainAsBad') ? undefined : json['TreatUncertainAsBad'],
        'PercentDataBad': !exists(json, 'PercentDataBad') ? undefined : json['PercentDataBad'],
        'PercentDataGood': !exists(json, 'PercentDataGood') ? undefined : json['PercentDataGood'],
        'UseSlopedExtrapolation': !exists(json, 'UseSlopedExtrapolation') ? undefined : json['UseSlopedExtrapolation'],
    };
}

export function AggregateConfigurationToJSON(value?: AggregateConfiguration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'UseServerCapabilitiesDefaults': value.UseServerCapabilitiesDefaults,
        'TreatUncertainAsBad': value.TreatUncertainAsBad,
        'PercentDataBad': value.PercentDataBad,
        'PercentDataGood': value.PercentDataGood,
        'UseSlopedExtrapolation': value.UseSlopedExtrapolation,
    };
}

