/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BrowseNextResponse } from './BrowseNextResponse';
import {
    BrowseNextResponseFromJSON,
    BrowseNextResponseFromJSONTyped,
    BrowseNextResponseToJSON,
} from './BrowseNextResponse';

/**
 * 
 * @export
 * @interface BrowseNextResponseMessage
 */
export interface BrowseNextResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseNextResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseNextResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BrowseNextResponseMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {BrowseNextResponse}
     * @memberof BrowseNextResponseMessage
     */
    Body?: BrowseNextResponse;
}

/**
 * Check if a given object implements the BrowseNextResponseMessage interface.
 */
export function instanceOfBrowseNextResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BrowseNextResponseMessageFromJSON(json: any): BrowseNextResponseMessage {
    return BrowseNextResponseMessageFromJSONTyped(json, false);
}

export function BrowseNextResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowseNextResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : BrowseNextResponseFromJSON(json['Body']),
    };
}

export function BrowseNextResponseMessageToJSON(value?: BrowseNextResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': BrowseNextResponseToJSON(value.Body),
    };
}

