/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BrowseNextRequest } from './BrowseNextRequest';
import {
    BrowseNextRequestFromJSON,
    BrowseNextRequestFromJSONTyped,
    BrowseNextRequestToJSON,
} from './BrowseNextRequest';

/**
 * 
 * @export
 * @interface BrowseNextRequestMessage
 */
export interface BrowseNextRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseNextRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseNextRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseNextRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BrowseNextRequestMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {BrowseNextRequest}
     * @memberof BrowseNextRequestMessage
     */
    Body?: BrowseNextRequest;
}

/**
 * Check if a given object implements the BrowseNextRequestMessage interface.
 */
export function instanceOfBrowseNextRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BrowseNextRequestMessageFromJSON(json: any): BrowseNextRequestMessage {
    return BrowseNextRequestMessageFromJSONTyped(json, false);
}

export function BrowseNextRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowseNextRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : BrowseNextRequestFromJSON(json['Body']),
    };
}

export function BrowseNextRequestMessageToJSON(value?: BrowseNextRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': BrowseNextRequestToJSON(value.Body),
    };
}

