/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BrowsePathTarget } from './BrowsePathTarget';
import {
    BrowsePathTargetFromJSON,
    BrowsePathTargetFromJSONTyped,
    BrowsePathTargetToJSON,
} from './BrowsePathTarget';

/**
 * 
 * @export
 * @interface BrowsePathResult
 */
export interface BrowsePathResult {
    /**
     * 
     * @type {number}
     * @memberof BrowsePathResult
     */
    StatusCode?: number;
    /**
     * 
     * @type {Array<BrowsePathTarget>}
     * @memberof BrowsePathResult
     */
    Targets?: Array<BrowsePathTarget>;
}

/**
 * Check if a given object implements the BrowsePathResult interface.
 */
export function instanceOfBrowsePathResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BrowsePathResultFromJSON(json: any): BrowsePathResult {
    return BrowsePathResultFromJSONTyped(json, false);
}

export function BrowsePathResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowsePathResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'StatusCode': !exists(json, 'StatusCode') ? undefined : json['StatusCode'],
        'Targets': !exists(json, 'Targets') ? undefined : ((json['Targets'] as Array<any>).map(BrowsePathTargetFromJSON)),
    };
}

export function BrowsePathResultToJSON(value?: BrowsePathResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'StatusCode': value.StatusCode,
        'Targets': value.Targets === undefined ? undefined : ((value.Targets as Array<any>).map(BrowsePathTargetToJSON)),
    };
}

