/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface BrowseNextRequest
 */
export interface BrowseNextRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof BrowseNextRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {boolean}
     * @memberof BrowseNextRequest
     */
    ReleaseContinuationPoints?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseNextRequest
     */
    ContinuationPoints?: Array<string>;
}

/**
 * Check if a given object implements the BrowseNextRequest interface.
 */
export function instanceOfBrowseNextRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BrowseNextRequestFromJSON(json: any): BrowseNextRequest {
    return BrowseNextRequestFromJSONTyped(json, false);
}

export function BrowseNextRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowseNextRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'ReleaseContinuationPoints': !exists(json, 'ReleaseContinuationPoints') ? undefined : json['ReleaseContinuationPoints'],
        'ContinuationPoints': !exists(json, 'ContinuationPoints') ? undefined : json['ContinuationPoints'],
    };
}

export function BrowseNextRequestToJSON(value?: BrowseNextRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'ReleaseContinuationPoints': value.ReleaseContinuationPoints,
        'ContinuationPoints': value.ContinuationPoints,
    };
}

