/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BrowseResponse } from './BrowseResponse';
import {
    BrowseResponseFromJSON,
    BrowseResponseFromJSONTyped,
    BrowseResponseToJSON,
} from './BrowseResponse';

/**
 * 
 * @export
 * @interface BrowseResponseMessage
 */
export interface BrowseResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof BrowseResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof BrowseResponseMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {BrowseResponse}
     * @memberof BrowseResponseMessage
     */
    Body?: BrowseResponse;
}

/**
 * Check if a given object implements the BrowseResponseMessage interface.
 */
export function instanceOfBrowseResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BrowseResponseMessageFromJSON(json: any): BrowseResponseMessage {
    return BrowseResponseMessageFromJSONTyped(json, false);
}

export function BrowseResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrowseResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : BrowseResponseFromJSON(json['Body']),
    };
}

export function BrowseResponseMessageToJSON(value?: BrowseResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': BrowseResponseToJSON(value.Body),
    };
}

