/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CallMethodResult } from './CallMethodResult';
import {
    CallMethodResultFromJSON,
    CallMethodResultFromJSONTyped,
    CallMethodResultToJSON,
} from './CallMethodResult';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
} from './DiagnosticInfo';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
} from './ResponseHeader';

/**
 * 
 * @export
 * @interface CallResponse
 */
export interface CallResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof CallResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<CallMethodResult>}
     * @memberof CallResponse
     */
    Results?: Array<CallMethodResult>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof CallResponse
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the CallResponse interface.
 */
export function instanceOfCallResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CallResponseFromJSON(json: any): CallResponse {
    return CallResponseFromJSONTyped(json, false);
}

export function CallResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ResponseHeader': !exists(json, 'ResponseHeader') ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'Results': !exists(json, 'Results') ? undefined : ((json['Results'] as Array<any>).map(CallMethodResultFromJSON)),
        'DiagnosticInfos': !exists(json, 'DiagnosticInfos') ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

export function CallResponseToJSON(value?: CallResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value.ResponseHeader),
        'Results': value.Results === undefined ? undefined : ((value.Results as Array<any>).map(CallMethodResultToJSON)),
        'DiagnosticInfos': value.DiagnosticInfos === undefined ? undefined : ((value.DiagnosticInfos as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

