/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CallRequest } from './CallRequest';
import {
    CallRequestFromJSON,
    CallRequestFromJSONTyped,
    CallRequestToJSON,
} from './CallRequest';

/**
 * 
 * @export
 * @interface CallRequestMessage
 */
export interface CallRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CallRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CallRequestMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {CallRequest}
     * @memberof CallRequestMessage
     */
    Body?: CallRequest;
}

/**
 * Check if a given object implements the CallRequestMessage interface.
 */
export function instanceOfCallRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CallRequestMessageFromJSON(json: any): CallRequestMessage {
    return CallRequestMessageFromJSONTyped(json, false);
}

export function CallRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : CallRequestFromJSON(json['Body']),
    };
}

export function CallRequestMessageToJSON(value?: CallRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': CallRequestToJSON(value.Body),
    };
}

