/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CallResponse } from './CallResponse';
import {
    CallResponseFromJSON,
    CallResponseFromJSONTyped,
    CallResponseToJSON,
} from './CallResponse';

/**
 * 
 * @export
 * @interface CallResponseMessage
 */
export interface CallResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof CallResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CallResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof CallResponseMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {CallResponse}
     * @memberof CallResponseMessage
     */
    Body?: CallResponse;
}

/**
 * Check if a given object implements the CallResponseMessage interface.
 */
export function instanceOfCallResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CallResponseMessageFromJSON(json: any): CallResponseMessage {
    return CallResponseMessageFromJSONTyped(json, false);
}

export function CallResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : CallResponseFromJSON(json['Body']),
    };
}

export function CallResponseMessageToJSON(value?: CallResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': CallResponseToJSON(value.Body),
    };
}

