/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CallMethodRequest } from './CallMethodRequest';
import {
    CallMethodRequestFromJSON,
    CallMethodRequestFromJSONTyped,
    CallMethodRequestToJSON,
} from './CallMethodRequest';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface CallRequest
 */
export interface CallRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof CallRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<CallMethodRequest>}
     * @memberof CallRequest
     */
    MethodsToCall?: Array<CallMethodRequest>;
}

/**
 * Check if a given object implements the CallRequest interface.
 */
export function instanceOfCallRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CallRequestFromJSON(json: any): CallRequest {
    return CallRequestFromJSONTyped(json, false);
}

export function CallRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CallRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'MethodsToCall': !exists(json, 'MethodsToCall') ? undefined : ((json['MethodsToCall'] as Array<any>).map(CallMethodRequestFromJSON)),
    };
}

export function CallRequestToJSON(value?: CallRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'MethodsToCall': value.MethodsToCall === undefined ? undefined : ((value.MethodsToCall as Array<any>).map(CallMethodRequestToJSON)),
    };
}

