/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConfigurationVersionDataType } from './ConfigurationVersionDataType';
import {
    ConfigurationVersionDataTypeFromJSON,
    ConfigurationVersionDataTypeFromJSONTyped,
    ConfigurationVersionDataTypeToJSON,
} from './ConfigurationVersionDataType';
import type { EnumDescription } from './EnumDescription';
import {
    EnumDescriptionFromJSON,
    EnumDescriptionFromJSONTyped,
    EnumDescriptionToJSON,
} from './EnumDescription';
import type { FieldMetaData } from './FieldMetaData';
import {
    FieldMetaDataFromJSON,
    FieldMetaDataFromJSONTyped,
    FieldMetaDataToJSON,
} from './FieldMetaData';
import type { LocalizedText } from './LocalizedText';
import {
    LocalizedTextFromJSON,
    LocalizedTextFromJSONTyped,
    LocalizedTextToJSON,
} from './LocalizedText';
import type { SimpleTypeDescription } from './SimpleTypeDescription';
import {
    SimpleTypeDescriptionFromJSON,
    SimpleTypeDescriptionFromJSONTyped,
    SimpleTypeDescriptionToJSON,
} from './SimpleTypeDescription';
import type { StructureDescription } from './StructureDescription';
import {
    StructureDescriptionFromJSON,
    StructureDescriptionFromJSONTyped,
    StructureDescriptionToJSON,
} from './StructureDescription';

/**
 * 
 * @export
 * @interface DataSetMetaDataType
 */
export interface DataSetMetaDataType {
    /**
     * 
     * @type {string}
     * @memberof DataSetMetaDataType
     */
    Name?: string;
    /**
     * 
     * @type {LocalizedText}
     * @memberof DataSetMetaDataType
     */
    Description?: LocalizedText;
    /**
     * 
     * @type {Array<FieldMetaData>}
     * @memberof DataSetMetaDataType
     */
    Fields?: Array<FieldMetaData>;
    /**
     * 
     * @type {string}
     * @memberof DataSetMetaDataType
     */
    DataSetClassId?: string;
    /**
     * 
     * @type {ConfigurationVersionDataType}
     * @memberof DataSetMetaDataType
     */
    ConfigurationVersion?: ConfigurationVersionDataType;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataSetMetaDataType
     */
    Namespaces?: Array<string>;
    /**
     * 
     * @type {Array<StructureDescription>}
     * @memberof DataSetMetaDataType
     */
    StructureDataTypes?: Array<StructureDescription>;
    /**
     * 
     * @type {Array<EnumDescription>}
     * @memberof DataSetMetaDataType
     */
    EnumDataTypes?: Array<EnumDescription>;
    /**
     * 
     * @type {Array<SimpleTypeDescription>}
     * @memberof DataSetMetaDataType
     */
    SimpleDataTypes?: Array<SimpleTypeDescription>;
}

/**
 * Check if a given object implements the DataSetMetaDataType interface.
 */
export function instanceOfDataSetMetaDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DataSetMetaDataTypeFromJSON(json: any): DataSetMetaDataType {
    return DataSetMetaDataTypeFromJSONTyped(json, false);
}

export function DataSetMetaDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetMetaDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Description': !exists(json, 'Description') ? undefined : LocalizedTextFromJSON(json['Description']),
        'Fields': !exists(json, 'Fields') ? undefined : ((json['Fields'] as Array<any>).map(FieldMetaDataFromJSON)),
        'DataSetClassId': !exists(json, 'DataSetClassId') ? undefined : json['DataSetClassId'],
        'ConfigurationVersion': !exists(json, 'ConfigurationVersion') ? undefined : ConfigurationVersionDataTypeFromJSON(json['ConfigurationVersion']),
        'Namespaces': !exists(json, 'Namespaces') ? undefined : json['Namespaces'],
        'StructureDataTypes': !exists(json, 'StructureDataTypes') ? undefined : ((json['StructureDataTypes'] as Array<any>).map(StructureDescriptionFromJSON)),
        'EnumDataTypes': !exists(json, 'EnumDataTypes') ? undefined : ((json['EnumDataTypes'] as Array<any>).map(EnumDescriptionFromJSON)),
        'SimpleDataTypes': !exists(json, 'SimpleDataTypes') ? undefined : ((json['SimpleDataTypes'] as Array<any>).map(SimpleTypeDescriptionFromJSON)),
    };
}

export function DataSetMetaDataTypeToJSON(value?: DataSetMetaDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.Name,
        'Description': LocalizedTextToJSON(value.Description),
        'Fields': value.Fields === undefined ? undefined : ((value.Fields as Array<any>).map(FieldMetaDataToJSON)),
        'DataSetClassId': value.DataSetClassId,
        'ConfigurationVersion': ConfigurationVersionDataTypeToJSON(value.ConfigurationVersion),
        'Namespaces': value.Namespaces,
        'StructureDataTypes': value.StructureDataTypes === undefined ? undefined : ((value.StructureDataTypes as Array<any>).map(StructureDescriptionToJSON)),
        'EnumDataTypes': value.EnumDataTypes === undefined ? undefined : ((value.EnumDataTypes as Array<any>).map(EnumDescriptionToJSON)),
        'SimpleDataTypes': value.SimpleDataTypes === undefined ? undefined : ((value.SimpleDataTypes as Array<any>).map(SimpleTypeDescriptionToJSON)),
    };
}

