/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExtensionObject } from './ExtensionObject';
import {
    ExtensionObjectFromJSON,
    ExtensionObjectFromJSONTyped,
    ExtensionObjectToJSON,
} from './ExtensionObject';
import type { KeyValuePair } from './KeyValuePair';
import {
    KeyValuePairFromJSON,
    KeyValuePairFromJSONTyped,
    KeyValuePairToJSON,
} from './KeyValuePair';

/**
 * 
 * @export
 * @interface DataSetWriterDataType
 */
export interface DataSetWriterDataType {
    /**
     * 
     * @type {string}
     * @memberof DataSetWriterDataType
     */
    Name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DataSetWriterDataType
     */
    Enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DataSetWriterDataType
     */
    DataSetWriterId?: number;
    /**
     * 
     * @type {number}
     * @memberof DataSetWriterDataType
     */
    DataSetFieldContentMask?: number;
    /**
     * 
     * @type {number}
     * @memberof DataSetWriterDataType
     */
    KeyFrameCount?: number;
    /**
     * 
     * @type {string}
     * @memberof DataSetWriterDataType
     */
    DataSetName?: string;
    /**
     * 
     * @type {Array<KeyValuePair>}
     * @memberof DataSetWriterDataType
     */
    DataSetWriterProperties?: Array<KeyValuePair>;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof DataSetWriterDataType
     */
    TransportSettings?: ExtensionObject;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof DataSetWriterDataType
     */
    MessageSettings?: ExtensionObject;
}

/**
 * Check if a given object implements the DataSetWriterDataType interface.
 */
export function instanceOfDataSetWriterDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DataSetWriterDataTypeFromJSON(json: any): DataSetWriterDataType {
    return DataSetWriterDataTypeFromJSONTyped(json, false);
}

export function DataSetWriterDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetWriterDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Enabled': !exists(json, 'Enabled') ? undefined : json['Enabled'],
        'DataSetWriterId': !exists(json, 'DataSetWriterId') ? undefined : json['DataSetWriterId'],
        'DataSetFieldContentMask': !exists(json, 'DataSetFieldContentMask') ? undefined : json['DataSetFieldContentMask'],
        'KeyFrameCount': !exists(json, 'KeyFrameCount') ? undefined : json['KeyFrameCount'],
        'DataSetName': !exists(json, 'DataSetName') ? undefined : json['DataSetName'],
        'DataSetWriterProperties': !exists(json, 'DataSetWriterProperties') ? undefined : ((json['DataSetWriterProperties'] as Array<any>).map(KeyValuePairFromJSON)),
        'TransportSettings': !exists(json, 'TransportSettings') ? undefined : ExtensionObjectFromJSON(json['TransportSettings']),
        'MessageSettings': !exists(json, 'MessageSettings') ? undefined : ExtensionObjectFromJSON(json['MessageSettings']),
    };
}

export function DataSetWriterDataTypeToJSON(value?: DataSetWriterDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.Name,
        'Enabled': value.Enabled,
        'DataSetWriterId': value.DataSetWriterId,
        'DataSetFieldContentMask': value.DataSetFieldContentMask,
        'KeyFrameCount': value.KeyFrameCount,
        'DataSetName': value.DataSetName,
        'DataSetWriterProperties': value.DataSetWriterProperties === undefined ? undefined : ((value.DataSetWriterProperties as Array<any>).map(KeyValuePairToJSON)),
        'TransportSettings': ExtensionObjectToJSON(value.TransportSettings),
        'MessageSettings': ExtensionObjectToJSON(value.MessageSettings),
    };
}

