/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApplicationDescription } from './ApplicationDescription';
import {
    ApplicationDescriptionFromJSON,
    ApplicationDescriptionFromJSONTyped,
    ApplicationDescriptionToJSON,
} from './ApplicationDescription';
import type { UserTokenPolicy } from './UserTokenPolicy';
import {
    UserTokenPolicyFromJSON,
    UserTokenPolicyFromJSONTyped,
    UserTokenPolicyToJSON,
} from './UserTokenPolicy';

/**
 * 
 * @export
 * @interface EndpointDescription
 */
export interface EndpointDescription {
    /**
     * 
     * @type {string}
     * @memberof EndpointDescription
     */
    EndpointUrl?: string;
    /**
     * 
     * @type {ApplicationDescription}
     * @memberof EndpointDescription
     */
    Server?: ApplicationDescription;
    /**
     * 
     * @type {string}
     * @memberof EndpointDescription
     */
    ServerCertificate?: string;
    /**
     * 
     * @type {number}
     * @memberof EndpointDescription
     */
    SecurityMode?: number;
    /**
     * 
     * @type {string}
     * @memberof EndpointDescription
     */
    SecurityPolicyUri?: string;
    /**
     * 
     * @type {Array<UserTokenPolicy>}
     * @memberof EndpointDescription
     */
    UserIdentityTokens?: Array<UserTokenPolicy>;
    /**
     * 
     * @type {string}
     * @memberof EndpointDescription
     */
    TransportProfileUri?: string;
    /**
     * 
     * @type {number}
     * @memberof EndpointDescription
     */
    SecurityLevel?: number;
}

/**
 * Check if a given object implements the EndpointDescription interface.
 */
export function instanceOfEndpointDescription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EndpointDescriptionFromJSON(json: any): EndpointDescription {
    return EndpointDescriptionFromJSONTyped(json, false);
}

export function EndpointDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndpointDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'EndpointUrl': !exists(json, 'EndpointUrl') ? undefined : json['EndpointUrl'],
        'Server': !exists(json, 'Server') ? undefined : ApplicationDescriptionFromJSON(json['Server']),
        'ServerCertificate': !exists(json, 'ServerCertificate') ? undefined : json['ServerCertificate'],
        'SecurityMode': !exists(json, 'SecurityMode') ? undefined : json['SecurityMode'],
        'SecurityPolicyUri': !exists(json, 'SecurityPolicyUri') ? undefined : json['SecurityPolicyUri'],
        'UserIdentityTokens': !exists(json, 'UserIdentityTokens') ? undefined : ((json['UserIdentityTokens'] as Array<any>).map(UserTokenPolicyFromJSON)),
        'TransportProfileUri': !exists(json, 'TransportProfileUri') ? undefined : json['TransportProfileUri'],
        'SecurityLevel': !exists(json, 'SecurityLevel') ? undefined : json['SecurityLevel'],
    };
}

export function EndpointDescriptionToJSON(value?: EndpointDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'EndpointUrl': value.EndpointUrl,
        'Server': ApplicationDescriptionToJSON(value.Server),
        'ServerCertificate': value.ServerCertificate,
        'SecurityMode': value.SecurityMode,
        'SecurityPolicyUri': value.SecurityPolicyUri,
        'UserIdentityTokens': value.UserIdentityTokens === undefined ? undefined : ((value.UserIdentityTokens as Array<any>).map(UserTokenPolicyToJSON)),
        'TransportProfileUri': value.TransportProfileUri,
        'SecurityLevel': value.SecurityLevel,
    };
}

