/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocalizedText } from './LocalizedText';
import {
    LocalizedTextFromJSON,
    LocalizedTextFromJSONTyped,
    LocalizedTextToJSON,
} from './LocalizedText';

/**
 * 
 * @export
 * @interface EnumField
 */
export interface EnumField {
    /**
     * 
     * @type {string}
     * @memberof EnumField
     */
    Name?: string;
    /**
     * 
     * @type {number}
     * @memberof EnumField
     */
    Value?: number;
    /**
     * 
     * @type {LocalizedText}
     * @memberof EnumField
     */
    DisplayName?: LocalizedText;
    /**
     * 
     * @type {LocalizedText}
     * @memberof EnumField
     */
    Description?: LocalizedText;
}

/**
 * Check if a given object implements the EnumField interface.
 */
export function instanceOfEnumField(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EnumFieldFromJSON(json: any): EnumField {
    return EnumFieldFromJSONTyped(json, false);
}

export function EnumFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Value': !exists(json, 'Value') ? undefined : json['Value'],
        'DisplayName': !exists(json, 'DisplayName') ? undefined : LocalizedTextFromJSON(json['DisplayName']),
        'Description': !exists(json, 'Description') ? undefined : LocalizedTextFromJSON(json['Description']),
    };
}

export function EnumFieldToJSON(value?: EnumField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.Name,
        'Value': value.Value,
        'DisplayName': LocalizedTextToJSON(value.DisplayName),
        'Description': LocalizedTextToJSON(value.Description),
    };
}

