/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EnumField } from './EnumField';
import {
    EnumFieldFromJSON,
    EnumFieldFromJSONTyped,
    EnumFieldToJSON,
} from './EnumField';

/**
 * 
 * @export
 * @interface EnumDefinition
 */
export interface EnumDefinition {
    /**
     * 
     * @type {Array<EnumField>}
     * @memberof EnumDefinition
     */
    Fields?: Array<EnumField>;
}

/**
 * Check if a given object implements the EnumDefinition interface.
 */
export function instanceOfEnumDefinition(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EnumDefinitionFromJSON(json: any): EnumDefinition {
    return EnumDefinitionFromJSONTyped(json, false);
}

export function EnumDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnumDefinition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Fields': !exists(json, 'Fields') ? undefined : ((json['Fields'] as Array<any>).map(EnumFieldFromJSON)),
    };
}

export function EnumDefinitionToJSON(value?: EnumDefinition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Fields': value.Fields === undefined ? undefined : ((value.Fields as Array<any>).map(EnumFieldToJSON)),
    };
}

