/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExpandedNodeId
 */
export interface ExpandedNodeId {
    /**
     * 
     * @type {number}
     * @memberof ExpandedNodeId
     */
    IdType?: number;
    /**
     * 
     * @type {any}
     * @memberof ExpandedNodeId
     */
    Id?: any | null;
    /**
     * 
     * @type {any}
     * @memberof ExpandedNodeId
     */
    Namespace?: any | null;
    /**
     * 
     * @type {number}
     * @memberof ExpandedNodeId
     */
    ServerUri?: number;
}

/**
 * Check if a given object implements the ExpandedNodeId interface.
 */
export function instanceOfExpandedNodeId(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExpandedNodeIdFromJSON(json: any): ExpandedNodeId {
    return ExpandedNodeIdFromJSONTyped(json, false);
}

export function ExpandedNodeIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpandedNodeId {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'IdType': !exists(json, 'IdType') ? undefined : json['IdType'],
        'Id': !exists(json, 'Id') ? undefined : json['Id'],
        'Namespace': !exists(json, 'Namespace') ? undefined : json['Namespace'],
        'ServerUri': !exists(json, 'ServerUri') ? undefined : json['ServerUri'],
    };
}

export function ExpandedNodeIdToJSON(value?: ExpandedNodeId | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'IdType': value.IdType,
        'Id': value.Id,
        'Namespace': value.Namespace,
        'ServerUri': value.ServerUri,
    };
}

