/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataValue } from './DataValue';
import {
    DataValueFromJSON,
    DataValueFromJSONTyped,
    DataValueToJSON,
} from './DataValue';

/**
 * 
 * @export
 * @interface HistoryData
 */
export interface HistoryData {
    /**
     * 
     * @type {Array<DataValue>}
     * @memberof HistoryData
     */
    DataValues?: Array<DataValue>;
}

/**
 * Check if a given object implements the HistoryData interface.
 */
export function instanceOfHistoryData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryDataFromJSON(json: any): HistoryData {
    return HistoryDataFromJSONTyped(json, false);
}

export function HistoryDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'DataValues': !exists(json, 'DataValues') ? undefined : ((json['DataValues'] as Array<any>).map(DataValueFromJSON)),
    };
}

export function HistoryDataToJSON(value?: HistoryData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DataValues': value.DataValues === undefined ? undefined : ((value.DataValues as Array<any>).map(DataValueToJSON)),
    };
}

