/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HistoryUpdateResponse } from './HistoryUpdateResponse';
import {
    HistoryUpdateResponseFromJSON,
    HistoryUpdateResponseFromJSONTyped,
    HistoryUpdateResponseToJSON,
} from './HistoryUpdateResponse';

/**
 * 
 * @export
 * @interface HistoryUpdateResponseMessage
 */
export interface HistoryUpdateResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryUpdateResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryUpdateResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof HistoryUpdateResponseMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {HistoryUpdateResponse}
     * @memberof HistoryUpdateResponseMessage
     */
    Body?: HistoryUpdateResponse;
}

/**
 * Check if a given object implements the HistoryUpdateResponseMessage interface.
 */
export function instanceOfHistoryUpdateResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryUpdateResponseMessageFromJSON(json: any): HistoryUpdateResponseMessage {
    return HistoryUpdateResponseMessageFromJSONTyped(json, false);
}

export function HistoryUpdateResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryUpdateResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : HistoryUpdateResponseFromJSON(json['Body']),
    };
}

export function HistoryUpdateResponseMessageToJSON(value?: HistoryUpdateResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': HistoryUpdateResponseToJSON(value.Body),
    };
}

