/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const HistoryUpdateType = {
    Insert: 1,
    Replace: 2,
    Update: 3,
    Delete: 4
} as const;
export type HistoryUpdateType = typeof HistoryUpdateType[keyof typeof HistoryUpdateType];


export function HistoryUpdateTypeFromJSON(json: any): HistoryUpdateType {
    return HistoryUpdateTypeFromJSONTyped(json, false);
}

export function HistoryUpdateTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryUpdateType {
    return json as HistoryUpdateType;
}

export function HistoryUpdateTypeToJSON(value?: HistoryUpdateType | null): any {
    return value as any;
}

