/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExtensionObject } from './ExtensionObject';
import {
    ExtensionObjectFromJSON,
    ExtensionObjectFromJSONTyped,
    ExtensionObjectToJSON,
} from './ExtensionObject';

/**
 * 
 * @export
 * @interface HistoryReadResult
 */
export interface HistoryReadResult {
    /**
     * 
     * @type {number}
     * @memberof HistoryReadResult
     */
    StatusCode?: number;
    /**
     * 
     * @type {string}
     * @memberof HistoryReadResult
     */
    ContinuationPoint?: string;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof HistoryReadResult
     */
    HistoryData?: ExtensionObject;
}

/**
 * Check if a given object implements the HistoryReadResult interface.
 */
export function instanceOfHistoryReadResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryReadResultFromJSON(json: any): HistoryReadResult {
    return HistoryReadResultFromJSONTyped(json, false);
}

export function HistoryReadResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryReadResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'StatusCode': !exists(json, 'StatusCode') ? undefined : json['StatusCode'],
        'ContinuationPoint': !exists(json, 'ContinuationPoint') ? undefined : json['ContinuationPoint'],
        'HistoryData': !exists(json, 'HistoryData') ? undefined : ExtensionObjectFromJSON(json['HistoryData']),
    };
}

export function HistoryReadResultToJSON(value?: HistoryReadResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'StatusCode': value.StatusCode,
        'ContinuationPoint': value.ContinuationPoint,
        'HistoryData': ExtensionObjectToJSON(value.HistoryData),
    };
}

