/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
} from './DiagnosticInfo';

/**
 * 
 * @export
 * @interface HistoryUpdateResult
 */
export interface HistoryUpdateResult {
    /**
     * 
     * @type {number}
     * @memberof HistoryUpdateResult
     */
    StatusCode?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof HistoryUpdateResult
     */
    OperationResults?: Array<number>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof HistoryUpdateResult
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the HistoryUpdateResult interface.
 */
export function instanceOfHistoryUpdateResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryUpdateResultFromJSON(json: any): HistoryUpdateResult {
    return HistoryUpdateResultFromJSONTyped(json, false);
}

export function HistoryUpdateResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryUpdateResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'StatusCode': !exists(json, 'StatusCode') ? undefined : json['StatusCode'],
        'OperationResults': !exists(json, 'OperationResults') ? undefined : json['OperationResults'],
        'DiagnosticInfos': !exists(json, 'DiagnosticInfos') ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

export function HistoryUpdateResultToJSON(value?: HistoryUpdateResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'StatusCode': value.StatusCode,
        'OperationResults': value.OperationResults,
        'DiagnosticInfos': value.DiagnosticInfos === undefined ? undefined : ((value.DiagnosticInfos as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

