/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
} from './DiagnosticInfo';
import type { HistoryReadResult } from './HistoryReadResult';
import {
    HistoryReadResultFromJSON,
    HistoryReadResultFromJSONTyped,
    HistoryReadResultToJSON,
} from './HistoryReadResult';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
} from './ResponseHeader';

/**
 * 
 * @export
 * @interface HistoryReadResponse
 */
export interface HistoryReadResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof HistoryReadResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<HistoryReadResult>}
     * @memberof HistoryReadResponse
     */
    Results?: Array<HistoryReadResult>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof HistoryReadResponse
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the HistoryReadResponse interface.
 */
export function instanceOfHistoryReadResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryReadResponseFromJSON(json: any): HistoryReadResponse {
    return HistoryReadResponseFromJSONTyped(json, false);
}

export function HistoryReadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryReadResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ResponseHeader': !exists(json, 'ResponseHeader') ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'Results': !exists(json, 'Results') ? undefined : ((json['Results'] as Array<any>).map(HistoryReadResultFromJSON)),
        'DiagnosticInfos': !exists(json, 'DiagnosticInfos') ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

export function HistoryReadResponseToJSON(value?: HistoryReadResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value.ResponseHeader),
        'Results': value.Results === undefined ? undefined : ((value.Results as Array<any>).map(HistoryReadResultToJSON)),
        'DiagnosticInfos': value.DiagnosticInfos === undefined ? undefined : ((value.DiagnosticInfos as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

