/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HistoryEventFieldList } from './HistoryEventFieldList';
import {
    HistoryEventFieldListFromJSON,
    HistoryEventFieldListFromJSONTyped,
    HistoryEventFieldListToJSON,
} from './HistoryEventFieldList';

/**
 * 
 * @export
 * @interface HistoryEvent
 */
export interface HistoryEvent {
    /**
     * 
     * @type {Array<HistoryEventFieldList>}
     * @memberof HistoryEvent
     */
    Events?: Array<HistoryEventFieldList>;
}

/**
 * Check if a given object implements the HistoryEvent interface.
 */
export function instanceOfHistoryEvent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryEventFromJSON(json: any): HistoryEvent {
    return HistoryEventFromJSONTyped(json, false);
}

export function HistoryEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Events': !exists(json, 'Events') ? undefined : ((json['Events'] as Array<any>).map(HistoryEventFieldListFromJSON)),
    };
}

export function HistoryEventToJSON(value?: HistoryEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Events': value.Events === undefined ? undefined : ((value.Events as Array<any>).map(HistoryEventFieldListToJSON)),
    };
}

