/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HistoryUpdateRequest } from './HistoryUpdateRequest';
import {
    HistoryUpdateRequestFromJSON,
    HistoryUpdateRequestFromJSONTyped,
    HistoryUpdateRequestToJSON,
} from './HistoryUpdateRequest';

/**
 * 
 * @export
 * @interface HistoryUpdateRequestMessage
 */
export interface HistoryUpdateRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryUpdateRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryUpdateRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof HistoryUpdateRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof HistoryUpdateRequestMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {HistoryUpdateRequest}
     * @memberof HistoryUpdateRequestMessage
     */
    Body?: HistoryUpdateRequest;
}

/**
 * Check if a given object implements the HistoryUpdateRequestMessage interface.
 */
export function instanceOfHistoryUpdateRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryUpdateRequestMessageFromJSON(json: any): HistoryUpdateRequestMessage {
    return HistoryUpdateRequestMessageFromJSONTyped(json, false);
}

export function HistoryUpdateRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryUpdateRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : HistoryUpdateRequestFromJSON(json['Body']),
    };
}

export function HistoryUpdateRequestMessageToJSON(value?: HistoryUpdateRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': HistoryUpdateRequestToJSON(value.Body),
    };
}

