/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DiagnosticInfo } from './DiagnosticInfo';
import {
    DiagnosticInfoFromJSON,
    DiagnosticInfoFromJSONTyped,
    DiagnosticInfoToJSON,
} from './DiagnosticInfo';
import type { HistoryUpdateResult } from './HistoryUpdateResult';
import {
    HistoryUpdateResultFromJSON,
    HistoryUpdateResultFromJSONTyped,
    HistoryUpdateResultToJSON,
} from './HistoryUpdateResult';
import type { ResponseHeader } from './ResponseHeader';
import {
    ResponseHeaderFromJSON,
    ResponseHeaderFromJSONTyped,
    ResponseHeaderToJSON,
} from './ResponseHeader';

/**
 * 
 * @export
 * @interface HistoryUpdateResponse
 */
export interface HistoryUpdateResponse {
    /**
     * 
     * @type {ResponseHeader}
     * @memberof HistoryUpdateResponse
     */
    ResponseHeader?: ResponseHeader;
    /**
     * 
     * @type {Array<HistoryUpdateResult>}
     * @memberof HistoryUpdateResponse
     */
    Results?: Array<HistoryUpdateResult>;
    /**
     * 
     * @type {Array<DiagnosticInfo>}
     * @memberof HistoryUpdateResponse
     */
    DiagnosticInfos?: Array<DiagnosticInfo>;
}

/**
 * Check if a given object implements the HistoryUpdateResponse interface.
 */
export function instanceOfHistoryUpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HistoryUpdateResponseFromJSON(json: any): HistoryUpdateResponse {
    return HistoryUpdateResponseFromJSONTyped(json, false);
}

export function HistoryUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HistoryUpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ResponseHeader': !exists(json, 'ResponseHeader') ? undefined : ResponseHeaderFromJSON(json['ResponseHeader']),
        'Results': !exists(json, 'Results') ? undefined : ((json['Results'] as Array<any>).map(HistoryUpdateResultFromJSON)),
        'DiagnosticInfos': !exists(json, 'DiagnosticInfos') ? undefined : ((json['DiagnosticInfos'] as Array<any>).map(DiagnosticInfoFromJSON)),
    };
}

export function HistoryUpdateResponseToJSON(value?: HistoryUpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ResponseHeader': ResponseHeaderToJSON(value.ResponseHeader),
        'Results': value.Results === undefined ? undefined : ((value.Results as Array<any>).map(HistoryUpdateResultToJSON)),
        'DiagnosticInfos': value.DiagnosticInfos === undefined ? undefined : ((value.DiagnosticInfos as Array<any>).map(DiagnosticInfoToJSON)),
    };
}

