/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonWriterGroupMessageDataType
 */
export interface JsonWriterGroupMessageDataType {
    /**
     * 
     * @type {number}
     * @memberof JsonWriterGroupMessageDataType
     */
    NetworkMessageContentMask?: number;
}

/**
 * Check if a given object implements the JsonWriterGroupMessageDataType interface.
 */
export function instanceOfJsonWriterGroupMessageDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JsonWriterGroupMessageDataTypeFromJSON(json: any): JsonWriterGroupMessageDataType {
    return JsonWriterGroupMessageDataTypeFromJSONTyped(json, false);
}

export function JsonWriterGroupMessageDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonWriterGroupMessageDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NetworkMessageContentMask': !exists(json, 'NetworkMessageContentMask') ? undefined : json['NetworkMessageContentMask'],
    };
}

export function JsonWriterGroupMessageDataTypeToJSON(value?: JsonWriterGroupMessageDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NetworkMessageContentMask': value.NetworkMessageContentMask,
    };
}

