/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JsonDataSetWriterMessageDataType
 */
export interface JsonDataSetWriterMessageDataType {
    /**
     * 
     * @type {number}
     * @memberof JsonDataSetWriterMessageDataType
     */
    DataSetMessageContentMask?: number;
}

/**
 * Check if a given object implements the JsonDataSetWriterMessageDataType interface.
 */
export function instanceOfJsonDataSetWriterMessageDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JsonDataSetWriterMessageDataTypeFromJSON(json: any): JsonDataSetWriterMessageDataType {
    return JsonDataSetWriterMessageDataTypeFromJSONTyped(json, false);
}

export function JsonDataSetWriterMessageDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): JsonDataSetWriterMessageDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'DataSetMessageContentMask': !exists(json, 'DataSetMessageContentMask') ? undefined : json['DataSetMessageContentMask'],
    };
}

export function JsonDataSetWriterMessageDataTypeToJSON(value?: JsonDataSetWriterMessageDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DataSetMessageContentMask': value.DataSetMessageContentMask,
    };
}

