/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MessageSecurityMode = {
    Invalid: 0,
    None: 1,
    Sign: 2,
    SignAndEncrypt: 3
} as const;
export type MessageSecurityMode = typeof MessageSecurityMode[keyof typeof MessageSecurityMode];


export function MessageSecurityModeFromJSON(json: any): MessageSecurityMode {
    return MessageSecurityModeFromJSONTyped(json, false);
}

export function MessageSecurityModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageSecurityMode {
    return json as MessageSecurityMode;
}

export function MessageSecurityModeToJSON(value?: MessageSecurityMode | null): any {
    return value as any;
}

