/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModificationInfo
 */
export interface ModificationInfo {
    /**
     * 
     * @type {Date}
     * @memberof ModificationInfo
     */
    ModificationTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof ModificationInfo
     */
    UpdateType?: number;
    /**
     * 
     * @type {string}
     * @memberof ModificationInfo
     */
    UserName?: string;
}

/**
 * Check if a given object implements the ModificationInfo interface.
 */
export function instanceOfModificationInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ModificationInfoFromJSON(json: any): ModificationInfo {
    return ModificationInfoFromJSONTyped(json, false);
}

export function ModificationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModificationInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ModificationTime': !exists(json, 'ModificationTime') ? undefined : (new Date(json['ModificationTime'])),
        'UpdateType': !exists(json, 'UpdateType') ? undefined : json['UpdateType'],
        'UserName': !exists(json, 'UserName') ? undefined : json['UserName'],
    };
}

export function ModificationInfoToJSON(value?: ModificationInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ModificationTime': value.ModificationTime === undefined ? undefined : (value.ModificationTime.toISOString()),
        'UpdateType': value.UpdateType,
        'UserName': value.UserName,
    };
}

