/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { KeyValuePair } from './KeyValuePair';
import {
    KeyValuePairFromJSON,
    KeyValuePairFromJSONTyped,
    KeyValuePairToJSON,
} from './KeyValuePair';
import type { UserTokenPolicy } from './UserTokenPolicy';
import {
    UserTokenPolicyFromJSON,
    UserTokenPolicyFromJSONTyped,
    UserTokenPolicyToJSON,
} from './UserTokenPolicy';

/**
 * 
 * @export
 * @interface PubSubKeyPushTargetDataType
 */
export interface PubSubKeyPushTargetDataType {
    /**
     * 
     * @type {string}
     * @memberof PubSubKeyPushTargetDataType
     */
    ApplicationUri?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PubSubKeyPushTargetDataType
     */
    PushTargetFolder?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PubSubKeyPushTargetDataType
     */
    EndpointUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PubSubKeyPushTargetDataType
     */
    SecurityPolicyUri?: string;
    /**
     * 
     * @type {UserTokenPolicy}
     * @memberof PubSubKeyPushTargetDataType
     */
    UserTokenType?: UserTokenPolicy;
    /**
     * 
     * @type {number}
     * @memberof PubSubKeyPushTargetDataType
     */
    RequestedKeyCount?: number;
    /**
     * 
     * @type {number}
     * @memberof PubSubKeyPushTargetDataType
     */
    RetryInterval?: number;
    /**
     * 
     * @type {Array<KeyValuePair>}
     * @memberof PubSubKeyPushTargetDataType
     */
    PushTargetProperties?: Array<KeyValuePair>;
    /**
     * 
     * @type {Array<string>}
     * @memberof PubSubKeyPushTargetDataType
     */
    SecurityGroups?: Array<string>;
}

/**
 * Check if a given object implements the PubSubKeyPushTargetDataType interface.
 */
export function instanceOfPubSubKeyPushTargetDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PubSubKeyPushTargetDataTypeFromJSON(json: any): PubSubKeyPushTargetDataType {
    return PubSubKeyPushTargetDataTypeFromJSONTyped(json, false);
}

export function PubSubKeyPushTargetDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubSubKeyPushTargetDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ApplicationUri': !exists(json, 'ApplicationUri') ? undefined : json['ApplicationUri'],
        'PushTargetFolder': !exists(json, 'PushTargetFolder') ? undefined : json['PushTargetFolder'],
        'EndpointUrl': !exists(json, 'EndpointUrl') ? undefined : json['EndpointUrl'],
        'SecurityPolicyUri': !exists(json, 'SecurityPolicyUri') ? undefined : json['SecurityPolicyUri'],
        'UserTokenType': !exists(json, 'UserTokenType') ? undefined : UserTokenPolicyFromJSON(json['UserTokenType']),
        'RequestedKeyCount': !exists(json, 'RequestedKeyCount') ? undefined : json['RequestedKeyCount'],
        'RetryInterval': !exists(json, 'RetryInterval') ? undefined : json['RetryInterval'],
        'PushTargetProperties': !exists(json, 'PushTargetProperties') ? undefined : ((json['PushTargetProperties'] as Array<any>).map(KeyValuePairFromJSON)),
        'SecurityGroups': !exists(json, 'SecurityGroups') ? undefined : json['SecurityGroups'],
    };
}

export function PubSubKeyPushTargetDataTypeToJSON(value?: PubSubKeyPushTargetDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ApplicationUri': value.ApplicationUri,
        'PushTargetFolder': value.PushTargetFolder,
        'EndpointUrl': value.EndpointUrl,
        'SecurityPolicyUri': value.SecurityPolicyUri,
        'UserTokenType': UserTokenPolicyToJSON(value.UserTokenType),
        'RequestedKeyCount': value.RequestedKeyCount,
        'RetryInterval': value.RetryInterval,
        'PushTargetProperties': value.PushTargetProperties === undefined ? undefined : ((value.PushTargetProperties as Array<any>).map(KeyValuePairToJSON)),
        'SecurityGroups': value.SecurityGroups,
    };
}

