/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PubSubConnectionDataType } from './PubSubConnectionDataType';
import {
    PubSubConnectionDataTypeFromJSON,
    PubSubConnectionDataTypeFromJSONTyped,
    PubSubConnectionDataTypeToJSON,
} from './PubSubConnectionDataType';
import type { PublishedDataSetDataType } from './PublishedDataSetDataType';
import {
    PublishedDataSetDataTypeFromJSON,
    PublishedDataSetDataTypeFromJSONTyped,
    PublishedDataSetDataTypeToJSON,
} from './PublishedDataSetDataType';

/**
 * 
 * @export
 * @interface PubSubConfigurationDataType
 */
export interface PubSubConfigurationDataType {
    /**
     * 
     * @type {Array<PublishedDataSetDataType>}
     * @memberof PubSubConfigurationDataType
     */
    PublishedDataSets?: Array<PublishedDataSetDataType>;
    /**
     * 
     * @type {Array<PubSubConnectionDataType>}
     * @memberof PubSubConfigurationDataType
     */
    Connections?: Array<PubSubConnectionDataType>;
    /**
     * 
     * @type {boolean}
     * @memberof PubSubConfigurationDataType
     */
    Enabled?: boolean;
}

/**
 * Check if a given object implements the PubSubConfigurationDataType interface.
 */
export function instanceOfPubSubConfigurationDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PubSubConfigurationDataTypeFromJSON(json: any): PubSubConfigurationDataType {
    return PubSubConfigurationDataTypeFromJSONTyped(json, false);
}

export function PubSubConfigurationDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubSubConfigurationDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'PublishedDataSets': !exists(json, 'PublishedDataSets') ? undefined : ((json['PublishedDataSets'] as Array<any>).map(PublishedDataSetDataTypeFromJSON)),
        'Connections': !exists(json, 'Connections') ? undefined : ((json['Connections'] as Array<any>).map(PubSubConnectionDataTypeFromJSON)),
        'Enabled': !exists(json, 'Enabled') ? undefined : json['Enabled'],
    };
}

export function PubSubConfigurationDataTypeToJSON(value?: PubSubConfigurationDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PublishedDataSets': value.PublishedDataSets === undefined ? undefined : ((value.PublishedDataSets as Array<any>).map(PublishedDataSetDataTypeToJSON)),
        'Connections': value.Connections === undefined ? undefined : ((value.Connections as Array<any>).map(PubSubConnectionDataTypeToJSON)),
        'Enabled': value.Enabled,
    };
}

