/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EndpointDescription } from './EndpointDescription';
import {
    EndpointDescriptionFromJSON,
    EndpointDescriptionFromJSONTyped,
    EndpointDescriptionToJSON,
} from './EndpointDescription';
import type { KeyValuePair } from './KeyValuePair';
import {
    KeyValuePairFromJSON,
    KeyValuePairFromJSONTyped,
    KeyValuePairToJSON,
} from './KeyValuePair';

/**
 * 
 * @export
 * @interface PubSubGroupDataType
 */
export interface PubSubGroupDataType {
    /**
     * 
     * @type {string}
     * @memberof PubSubGroupDataType
     */
    Name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PubSubGroupDataType
     */
    Enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PubSubGroupDataType
     */
    SecurityMode?: number;
    /**
     * 
     * @type {string}
     * @memberof PubSubGroupDataType
     */
    SecurityGroupId?: string;
    /**
     * 
     * @type {Array<EndpointDescription>}
     * @memberof PubSubGroupDataType
     */
    SecurityKeyServices?: Array<EndpointDescription>;
    /**
     * 
     * @type {number}
     * @memberof PubSubGroupDataType
     */
    MaxNetworkMessageSize?: number;
    /**
     * 
     * @type {Array<KeyValuePair>}
     * @memberof PubSubGroupDataType
     */
    GroupProperties?: Array<KeyValuePair>;
}

/**
 * Check if a given object implements the PubSubGroupDataType interface.
 */
export function instanceOfPubSubGroupDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PubSubGroupDataTypeFromJSON(json: any): PubSubGroupDataType {
    return PubSubGroupDataTypeFromJSONTyped(json, false);
}

export function PubSubGroupDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubSubGroupDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Enabled': !exists(json, 'Enabled') ? undefined : json['Enabled'],
        'SecurityMode': !exists(json, 'SecurityMode') ? undefined : json['SecurityMode'],
        'SecurityGroupId': !exists(json, 'SecurityGroupId') ? undefined : json['SecurityGroupId'],
        'SecurityKeyServices': !exists(json, 'SecurityKeyServices') ? undefined : ((json['SecurityKeyServices'] as Array<any>).map(EndpointDescriptionFromJSON)),
        'MaxNetworkMessageSize': !exists(json, 'MaxNetworkMessageSize') ? undefined : json['MaxNetworkMessageSize'],
        'GroupProperties': !exists(json, 'GroupProperties') ? undefined : ((json['GroupProperties'] as Array<any>).map(KeyValuePairFromJSON)),
    };
}

export function PubSubGroupDataTypeToJSON(value?: PubSubGroupDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.Name,
        'Enabled': value.Enabled,
        'SecurityMode': value.SecurityMode,
        'SecurityGroupId': value.SecurityGroupId,
        'SecurityKeyServices': value.SecurityKeyServices === undefined ? undefined : ((value.SecurityKeyServices as Array<any>).map(EndpointDescriptionToJSON)),
        'MaxNetworkMessageSize': value.MaxNetworkMessageSize,
        'GroupProperties': value.GroupProperties === undefined ? undefined : ((value.GroupProperties as Array<any>).map(KeyValuePairToJSON)),
    };
}

