/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExtensionObject } from './ExtensionObject';
import {
    ExtensionObjectFromJSON,
    ExtensionObjectFromJSONTyped,
    ExtensionObjectToJSON,
} from './ExtensionObject';
import type { KeyValuePair } from './KeyValuePair';
import {
    KeyValuePairFromJSON,
    KeyValuePairFromJSONTyped,
    KeyValuePairToJSON,
} from './KeyValuePair';
import type { ReaderGroupDataType } from './ReaderGroupDataType';
import {
    ReaderGroupDataTypeFromJSON,
    ReaderGroupDataTypeFromJSONTyped,
    ReaderGroupDataTypeToJSON,
} from './ReaderGroupDataType';
import type { WriterGroupDataType } from './WriterGroupDataType';
import {
    WriterGroupDataTypeFromJSON,
    WriterGroupDataTypeFromJSONTyped,
    WriterGroupDataTypeToJSON,
} from './WriterGroupDataType';

/**
 * 
 * @export
 * @interface PubSubConnectionDataType
 */
export interface PubSubConnectionDataType {
    /**
     * 
     * @type {string}
     * @memberof PubSubConnectionDataType
     */
    Name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PubSubConnectionDataType
     */
    Enabled?: boolean;
    /**
     * 
     * @type {object}
     * @memberof PubSubConnectionDataType
     */
    PublisherId?: object;
    /**
     * 
     * @type {string}
     * @memberof PubSubConnectionDataType
     */
    TransportProfileUri?: string;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof PubSubConnectionDataType
     */
    Address?: ExtensionObject;
    /**
     * 
     * @type {Array<KeyValuePair>}
     * @memberof PubSubConnectionDataType
     */
    ConnectionProperties?: Array<KeyValuePair>;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof PubSubConnectionDataType
     */
    TransportSettings?: ExtensionObject;
    /**
     * 
     * @type {Array<WriterGroupDataType>}
     * @memberof PubSubConnectionDataType
     */
    WriterGroups?: Array<WriterGroupDataType>;
    /**
     * 
     * @type {Array<ReaderGroupDataType>}
     * @memberof PubSubConnectionDataType
     */
    ReaderGroups?: Array<ReaderGroupDataType>;
}

/**
 * Check if a given object implements the PubSubConnectionDataType interface.
 */
export function instanceOfPubSubConnectionDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PubSubConnectionDataTypeFromJSON(json: any): PubSubConnectionDataType {
    return PubSubConnectionDataTypeFromJSONTyped(json, false);
}

export function PubSubConnectionDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubSubConnectionDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Enabled': !exists(json, 'Enabled') ? undefined : json['Enabled'],
        'PublisherId': !exists(json, 'PublisherId') ? undefined : json['PublisherId'],
        'TransportProfileUri': !exists(json, 'TransportProfileUri') ? undefined : json['TransportProfileUri'],
        'Address': !exists(json, 'Address') ? undefined : ExtensionObjectFromJSON(json['Address']),
        'ConnectionProperties': !exists(json, 'ConnectionProperties') ? undefined : ((json['ConnectionProperties'] as Array<any>).map(KeyValuePairFromJSON)),
        'TransportSettings': !exists(json, 'TransportSettings') ? undefined : ExtensionObjectFromJSON(json['TransportSettings']),
        'WriterGroups': !exists(json, 'WriterGroups') ? undefined : ((json['WriterGroups'] as Array<any>).map(WriterGroupDataTypeFromJSON)),
        'ReaderGroups': !exists(json, 'ReaderGroups') ? undefined : ((json['ReaderGroups'] as Array<any>).map(ReaderGroupDataTypeFromJSON)),
    };
}

export function PubSubConnectionDataTypeToJSON(value?: PubSubConnectionDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.Name,
        'Enabled': value.Enabled,
        'PublisherId': value.PublisherId,
        'TransportProfileUri': value.TransportProfileUri,
        'Address': ExtensionObjectToJSON(value.Address),
        'ConnectionProperties': value.ConnectionProperties === undefined ? undefined : ((value.ConnectionProperties as Array<any>).map(KeyValuePairToJSON)),
        'TransportSettings': ExtensionObjectToJSON(value.TransportSettings),
        'WriterGroups': value.WriterGroups === undefined ? undefined : ((value.WriterGroups as Array<any>).map(WriterGroupDataTypeToJSON)),
        'ReaderGroups': value.ReaderGroups === undefined ? undefined : ((value.ReaderGroups as Array<any>).map(ReaderGroupDataTypeToJSON)),
    };
}

