/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataSetMetaDataType } from './DataSetMetaDataType';
import {
    DataSetMetaDataTypeFromJSON,
    DataSetMetaDataTypeFromJSONTyped,
    DataSetMetaDataTypeToJSON,
} from './DataSetMetaDataType';
import type { EndpointDescription } from './EndpointDescription';
import {
    EndpointDescriptionFromJSON,
    EndpointDescriptionFromJSONTyped,
    EndpointDescriptionToJSON,
} from './EndpointDescription';
import type { KeyValuePair } from './KeyValuePair';
import {
    KeyValuePairFromJSON,
    KeyValuePairFromJSONTyped,
    KeyValuePairToJSON,
} from './KeyValuePair';
import type { PubSubConnectionDataType } from './PubSubConnectionDataType';
import {
    PubSubConnectionDataTypeFromJSON,
    PubSubConnectionDataTypeFromJSONTyped,
    PubSubConnectionDataTypeToJSON,
} from './PubSubConnectionDataType';
import type { PubSubKeyPushTargetDataType } from './PubSubKeyPushTargetDataType';
import {
    PubSubKeyPushTargetDataTypeFromJSON,
    PubSubKeyPushTargetDataTypeFromJSONTyped,
    PubSubKeyPushTargetDataTypeToJSON,
} from './PubSubKeyPushTargetDataType';
import type { PublishedDataSetDataType } from './PublishedDataSetDataType';
import {
    PublishedDataSetDataTypeFromJSON,
    PublishedDataSetDataTypeFromJSONTyped,
    PublishedDataSetDataTypeToJSON,
} from './PublishedDataSetDataType';
import type { SecurityGroupDataType } from './SecurityGroupDataType';
import {
    SecurityGroupDataTypeFromJSON,
    SecurityGroupDataTypeFromJSONTyped,
    SecurityGroupDataTypeToJSON,
} from './SecurityGroupDataType';
import type { StandaloneSubscribedDataSetDataType } from './StandaloneSubscribedDataSetDataType';
import {
    StandaloneSubscribedDataSetDataTypeFromJSON,
    StandaloneSubscribedDataSetDataTypeFromJSONTyped,
    StandaloneSubscribedDataSetDataTypeToJSON,
} from './StandaloneSubscribedDataSetDataType';

/**
 * 
 * @export
 * @interface PubSubConfiguration2DataType
 */
export interface PubSubConfiguration2DataType {
    /**
     * 
     * @type {Array<StandaloneSubscribedDataSetDataType>}
     * @memberof PubSubConfiguration2DataType
     */
    SubscribedDataSets?: Array<StandaloneSubscribedDataSetDataType>;
    /**
     * 
     * @type {Array<DataSetMetaDataType>}
     * @memberof PubSubConfiguration2DataType
     */
    DataSetClasses?: Array<DataSetMetaDataType>;
    /**
     * 
     * @type {Array<EndpointDescription>}
     * @memberof PubSubConfiguration2DataType
     */
    DefaultSecurityKeyServices?: Array<EndpointDescription>;
    /**
     * 
     * @type {Array<SecurityGroupDataType>}
     * @memberof PubSubConfiguration2DataType
     */
    SecurityGroups?: Array<SecurityGroupDataType>;
    /**
     * 
     * @type {Array<PubSubKeyPushTargetDataType>}
     * @memberof PubSubConfiguration2DataType
     */
    PubSubKeyPushTargets?: Array<PubSubKeyPushTargetDataType>;
    /**
     * 
     * @type {number}
     * @memberof PubSubConfiguration2DataType
     */
    ConfigurationVersion?: number;
    /**
     * 
     * @type {Array<KeyValuePair>}
     * @memberof PubSubConfiguration2DataType
     */
    ConfigurationProperties?: Array<KeyValuePair>;
    /**
     * 
     * @type {Array<PublishedDataSetDataType>}
     * @memberof PubSubConfiguration2DataType
     */
    PublishedDataSets?: Array<PublishedDataSetDataType>;
    /**
     * 
     * @type {Array<PubSubConnectionDataType>}
     * @memberof PubSubConfiguration2DataType
     */
    Connections?: Array<PubSubConnectionDataType>;
    /**
     * 
     * @type {boolean}
     * @memberof PubSubConfiguration2DataType
     */
    Enabled?: boolean;
}

/**
 * Check if a given object implements the PubSubConfiguration2DataType interface.
 */
export function instanceOfPubSubConfiguration2DataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PubSubConfiguration2DataTypeFromJSON(json: any): PubSubConfiguration2DataType {
    return PubSubConfiguration2DataTypeFromJSONTyped(json, false);
}

export function PubSubConfiguration2DataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PubSubConfiguration2DataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'SubscribedDataSets': !exists(json, 'SubscribedDataSets') ? undefined : ((json['SubscribedDataSets'] as Array<any>).map(StandaloneSubscribedDataSetDataTypeFromJSON)),
        'DataSetClasses': !exists(json, 'DataSetClasses') ? undefined : ((json['DataSetClasses'] as Array<any>).map(DataSetMetaDataTypeFromJSON)),
        'DefaultSecurityKeyServices': !exists(json, 'DefaultSecurityKeyServices') ? undefined : ((json['DefaultSecurityKeyServices'] as Array<any>).map(EndpointDescriptionFromJSON)),
        'SecurityGroups': !exists(json, 'SecurityGroups') ? undefined : ((json['SecurityGroups'] as Array<any>).map(SecurityGroupDataTypeFromJSON)),
        'PubSubKeyPushTargets': !exists(json, 'PubSubKeyPushTargets') ? undefined : ((json['PubSubKeyPushTargets'] as Array<any>).map(PubSubKeyPushTargetDataTypeFromJSON)),
        'ConfigurationVersion': !exists(json, 'ConfigurationVersion') ? undefined : json['ConfigurationVersion'],
        'ConfigurationProperties': !exists(json, 'ConfigurationProperties') ? undefined : ((json['ConfigurationProperties'] as Array<any>).map(KeyValuePairFromJSON)),
        'PublishedDataSets': !exists(json, 'PublishedDataSets') ? undefined : ((json['PublishedDataSets'] as Array<any>).map(PublishedDataSetDataTypeFromJSON)),
        'Connections': !exists(json, 'Connections') ? undefined : ((json['Connections'] as Array<any>).map(PubSubConnectionDataTypeFromJSON)),
        'Enabled': !exists(json, 'Enabled') ? undefined : json['Enabled'],
    };
}

export function PubSubConfiguration2DataTypeToJSON(value?: PubSubConfiguration2DataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'SubscribedDataSets': value.SubscribedDataSets === undefined ? undefined : ((value.SubscribedDataSets as Array<any>).map(StandaloneSubscribedDataSetDataTypeToJSON)),
        'DataSetClasses': value.DataSetClasses === undefined ? undefined : ((value.DataSetClasses as Array<any>).map(DataSetMetaDataTypeToJSON)),
        'DefaultSecurityKeyServices': value.DefaultSecurityKeyServices === undefined ? undefined : ((value.DefaultSecurityKeyServices as Array<any>).map(EndpointDescriptionToJSON)),
        'SecurityGroups': value.SecurityGroups === undefined ? undefined : ((value.SecurityGroups as Array<any>).map(SecurityGroupDataTypeToJSON)),
        'PubSubKeyPushTargets': value.PubSubKeyPushTargets === undefined ? undefined : ((value.PubSubKeyPushTargets as Array<any>).map(PubSubKeyPushTargetDataTypeToJSON)),
        'ConfigurationVersion': value.ConfigurationVersion,
        'ConfigurationProperties': value.ConfigurationProperties === undefined ? undefined : ((value.ConfigurationProperties as Array<any>).map(KeyValuePairToJSON)),
        'PublishedDataSets': value.PublishedDataSets === undefined ? undefined : ((value.PublishedDataSets as Array<any>).map(PublishedDataSetDataTypeToJSON)),
        'Connections': value.Connections === undefined ? undefined : ((value.Connections as Array<any>).map(PubSubConnectionDataTypeToJSON)),
        'Enabled': value.Enabled,
    };
}

