/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadAnnotationDataDetails
 */
export interface ReadAnnotationDataDetails {
    /**
     * 
     * @type {Array<Date>}
     * @memberof ReadAnnotationDataDetails
     */
    ReqTimes?: Array<Date>;
}

/**
 * Check if a given object implements the ReadAnnotationDataDetails interface.
 */
export function instanceOfReadAnnotationDataDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadAnnotationDataDetailsFromJSON(json: any): ReadAnnotationDataDetails {
    return ReadAnnotationDataDetailsFromJSONTyped(json, false);
}

export function ReadAnnotationDataDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadAnnotationDataDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ReqTimes': !exists(json, 'ReqTimes') ? undefined : json['ReqTimes'],
    };
}

export function ReadAnnotationDataDetailsToJSON(value?: ReadAnnotationDataDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ReqTimes': value.ReqTimes,
    };
}

