/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadRawModifiedDetails
 */
export interface ReadRawModifiedDetails {
    /**
     * 
     * @type {boolean}
     * @memberof ReadRawModifiedDetails
     */
    IsReadModified?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ReadRawModifiedDetails
     */
    StartTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReadRawModifiedDetails
     */
    EndTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof ReadRawModifiedDetails
     */
    NumValuesPerNode?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReadRawModifiedDetails
     */
    ReturnBounds?: boolean;
}

/**
 * Check if a given object implements the ReadRawModifiedDetails interface.
 */
export function instanceOfReadRawModifiedDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadRawModifiedDetailsFromJSON(json: any): ReadRawModifiedDetails {
    return ReadRawModifiedDetailsFromJSONTyped(json, false);
}

export function ReadRawModifiedDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadRawModifiedDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'IsReadModified': !exists(json, 'IsReadModified') ? undefined : json['IsReadModified'],
        'StartTime': !exists(json, 'StartTime') ? undefined : (new Date(json['StartTime'])),
        'EndTime': !exists(json, 'EndTime') ? undefined : (new Date(json['EndTime'])),
        'NumValuesPerNode': !exists(json, 'NumValuesPerNode') ? undefined : json['NumValuesPerNode'],
        'ReturnBounds': !exists(json, 'ReturnBounds') ? undefined : json['ReturnBounds'],
    };
}

export function ReadRawModifiedDetailsToJSON(value?: ReadRawModifiedDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'IsReadModified': value.IsReadModified,
        'StartTime': value.StartTime === undefined ? undefined : (value.StartTime.toISOString()),
        'EndTime': value.EndTime === undefined ? undefined : (value.EndTime.toISOString()),
        'NumValuesPerNode': value.NumValuesPerNode,
        'ReturnBounds': value.ReturnBounds,
    };
}

