/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataSetReaderDataType } from './DataSetReaderDataType';
import {
    DataSetReaderDataTypeFromJSON,
    DataSetReaderDataTypeFromJSONTyped,
    DataSetReaderDataTypeToJSON,
} from './DataSetReaderDataType';
import type { EndpointDescription } from './EndpointDescription';
import {
    EndpointDescriptionFromJSON,
    EndpointDescriptionFromJSONTyped,
    EndpointDescriptionToJSON,
} from './EndpointDescription';
import type { ExtensionObject } from './ExtensionObject';
import {
    ExtensionObjectFromJSON,
    ExtensionObjectFromJSONTyped,
    ExtensionObjectToJSON,
} from './ExtensionObject';
import type { KeyValuePair } from './KeyValuePair';
import {
    KeyValuePairFromJSON,
    KeyValuePairFromJSONTyped,
    KeyValuePairToJSON,
} from './KeyValuePair';

/**
 * 
 * @export
 * @interface ReaderGroupDataType
 */
export interface ReaderGroupDataType {
    /**
     * 
     * @type {ExtensionObject}
     * @memberof ReaderGroupDataType
     */
    TransportSettings?: ExtensionObject;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof ReaderGroupDataType
     */
    MessageSettings?: ExtensionObject;
    /**
     * 
     * @type {Array<DataSetReaderDataType>}
     * @memberof ReaderGroupDataType
     */
    DataSetReaders?: Array<DataSetReaderDataType>;
    /**
     * 
     * @type {string}
     * @memberof ReaderGroupDataType
     */
    Name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ReaderGroupDataType
     */
    Enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ReaderGroupDataType
     */
    SecurityMode?: number;
    /**
     * 
     * @type {string}
     * @memberof ReaderGroupDataType
     */
    SecurityGroupId?: string;
    /**
     * 
     * @type {Array<EndpointDescription>}
     * @memberof ReaderGroupDataType
     */
    SecurityKeyServices?: Array<EndpointDescription>;
    /**
     * 
     * @type {number}
     * @memberof ReaderGroupDataType
     */
    MaxNetworkMessageSize?: number;
    /**
     * 
     * @type {Array<KeyValuePair>}
     * @memberof ReaderGroupDataType
     */
    GroupProperties?: Array<KeyValuePair>;
}

/**
 * Check if a given object implements the ReaderGroupDataType interface.
 */
export function instanceOfReaderGroupDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReaderGroupDataTypeFromJSON(json: any): ReaderGroupDataType {
    return ReaderGroupDataTypeFromJSONTyped(json, false);
}

export function ReaderGroupDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReaderGroupDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'TransportSettings': !exists(json, 'TransportSettings') ? undefined : ExtensionObjectFromJSON(json['TransportSettings']),
        'MessageSettings': !exists(json, 'MessageSettings') ? undefined : ExtensionObjectFromJSON(json['MessageSettings']),
        'DataSetReaders': !exists(json, 'DataSetReaders') ? undefined : ((json['DataSetReaders'] as Array<any>).map(DataSetReaderDataTypeFromJSON)),
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Enabled': !exists(json, 'Enabled') ? undefined : json['Enabled'],
        'SecurityMode': !exists(json, 'SecurityMode') ? undefined : json['SecurityMode'],
        'SecurityGroupId': !exists(json, 'SecurityGroupId') ? undefined : json['SecurityGroupId'],
        'SecurityKeyServices': !exists(json, 'SecurityKeyServices') ? undefined : ((json['SecurityKeyServices'] as Array<any>).map(EndpointDescriptionFromJSON)),
        'MaxNetworkMessageSize': !exists(json, 'MaxNetworkMessageSize') ? undefined : json['MaxNetworkMessageSize'],
        'GroupProperties': !exists(json, 'GroupProperties') ? undefined : ((json['GroupProperties'] as Array<any>).map(KeyValuePairFromJSON)),
    };
}

export function ReaderGroupDataTypeToJSON(value?: ReaderGroupDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TransportSettings': ExtensionObjectToJSON(value.TransportSettings),
        'MessageSettings': ExtensionObjectToJSON(value.MessageSettings),
        'DataSetReaders': value.DataSetReaders === undefined ? undefined : ((value.DataSetReaders as Array<any>).map(DataSetReaderDataTypeToJSON)),
        'Name': value.Name,
        'Enabled': value.Enabled,
        'SecurityMode': value.SecurityMode,
        'SecurityGroupId': value.SecurityGroupId,
        'SecurityKeyServices': value.SecurityKeyServices === undefined ? undefined : ((value.SecurityKeyServices as Array<any>).map(EndpointDescriptionToJSON)),
        'MaxNetworkMessageSize': value.MaxNetworkMessageSize,
        'GroupProperties': value.GroupProperties === undefined ? undefined : ((value.GroupProperties as Array<any>).map(KeyValuePairToJSON)),
    };
}

