/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadEventDetails2
 */
export interface ReadEventDetails2 {
    /**
     * 
     * @type {boolean}
     * @memberof ReadEventDetails2
     */
    ReadModified?: boolean;
}

/**
 * Check if a given object implements the ReadEventDetails2 interface.
 */
export function instanceOfReadEventDetails2(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadEventDetails2FromJSON(json: any): ReadEventDetails2 {
    return ReadEventDetails2FromJSONTyped(json, false);
}

export function ReadEventDetails2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadEventDetails2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ReadModified': !exists(json, 'ReadModified') ? undefined : json['ReadModified'],
    };
}

export function ReadEventDetails2ToJSON(value?: ReadEventDetails2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ReadModified': value.ReadModified,
    };
}

