/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadValueId } from './ReadValueId';
import {
    ReadValueIdFromJSON,
    ReadValueIdFromJSONTyped,
    ReadValueIdToJSON,
} from './ReadValueId';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface ReadRequest
 */
export interface ReadRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof ReadRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {number}
     * @memberof ReadRequest
     */
    MaxAge?: number;
    /**
     * 
     * @type {number}
     * @memberof ReadRequest
     */
    TimestampsToReturn?: number;
    /**
     * 
     * @type {Array<ReadValueId>}
     * @memberof ReadRequest
     */
    NodesToRead?: Array<ReadValueId>;
}

/**
 * Check if a given object implements the ReadRequest interface.
 */
export function instanceOfReadRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadRequestFromJSON(json: any): ReadRequest {
    return ReadRequestFromJSONTyped(json, false);
}

export function ReadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'MaxAge': !exists(json, 'MaxAge') ? undefined : json['MaxAge'],
        'TimestampsToReturn': !exists(json, 'TimestampsToReturn') ? undefined : json['TimestampsToReturn'],
        'NodesToRead': !exists(json, 'NodesToRead') ? undefined : ((json['NodesToRead'] as Array<any>).map(ReadValueIdFromJSON)),
    };
}

export function ReadRequestToJSON(value?: ReadRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'MaxAge': value.MaxAge,
        'TimestampsToReturn': value.TimestampsToReturn,
        'NodesToRead': value.NodesToRead === undefined ? undefined : ((value.NodesToRead as Array<any>).map(ReadValueIdToJSON)),
    };
}

