/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadAtTimeDetails
 */
export interface ReadAtTimeDetails {
    /**
     * 
     * @type {Array<Date>}
     * @memberof ReadAtTimeDetails
     */
    ReqTimes?: Array<Date>;
    /**
     * 
     * @type {boolean}
     * @memberof ReadAtTimeDetails
     */
    UseSimpleBounds?: boolean;
}

/**
 * Check if a given object implements the ReadAtTimeDetails interface.
 */
export function instanceOfReadAtTimeDetails(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadAtTimeDetailsFromJSON(json: any): ReadAtTimeDetails {
    return ReadAtTimeDetailsFromJSONTyped(json, false);
}

export function ReadAtTimeDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadAtTimeDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ReqTimes': !exists(json, 'ReqTimes') ? undefined : json['ReqTimes'],
        'UseSimpleBounds': !exists(json, 'UseSimpleBounds') ? undefined : json['UseSimpleBounds'],
    };
}

export function ReadAtTimeDetailsToJSON(value?: ReadAtTimeDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ReqTimes': value.ReqTimes,
        'UseSimpleBounds': value.UseSimpleBounds,
    };
}

