/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadRequest } from './ReadRequest';
import {
    ReadRequestFromJSON,
    ReadRequestFromJSONTyped,
    ReadRequestToJSON,
} from './ReadRequest';

/**
 * 
 * @export
 * @interface ReadRequestMessage
 */
export interface ReadRequestMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof ReadRequestMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReadRequestMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReadRequestMessage
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ReadRequestMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {ReadRequest}
     * @memberof ReadRequestMessage
     */
    Body?: ReadRequest;
}

/**
 * Check if a given object implements the ReadRequestMessage interface.
 */
export function instanceOfReadRequestMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadRequestMessageFromJSON(json: any): ReadRequestMessage {
    return ReadRequestMessageFromJSONTyped(json, false);
}

export function ReadRequestMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadRequestMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : ReadRequestFromJSON(json['Body']),
    };
}

export function ReadRequestMessageToJSON(value?: ReadRequestMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'LocaleIds': value.LocaleIds,
        'ServiceId': value.ServiceId,
        'Body': ReadRequestToJSON(value.Body),
    };
}

