/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReadResponse } from './ReadResponse';
import {
    ReadResponseFromJSON,
    ReadResponseFromJSONTyped,
    ReadResponseToJSON,
} from './ReadResponse';

/**
 * 
 * @export
 * @interface ReadResponseMessage
 */
export interface ReadResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof ReadResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReadResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ReadResponseMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {ReadResponse}
     * @memberof ReadResponseMessage
     */
    Body?: ReadResponse;
}

/**
 * Check if a given object implements the ReadResponseMessage interface.
 */
export function instanceOfReadResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadResponseMessageFromJSON(json: any): ReadResponseMessage {
    return ReadResponseMessageFromJSONTyped(json, false);
}

export function ReadResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : ReadResponseFromJSON(json['Body']),
    };
}

export function ReadResponseMessageToJSON(value?: ReadResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': ReadResponseToJSON(value.Body),
    };
}

