/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NodeId } from './NodeId';
import {
    NodeIdFromJSON,
    NodeIdFromJSONTyped,
    NodeIdToJSON,
} from './NodeId';
import type { QualifiedName } from './QualifiedName';
import {
    QualifiedNameFromJSON,
    QualifiedNameFromJSONTyped,
    QualifiedNameToJSON,
} from './QualifiedName';

/**
 * 
 * @export
 * @interface SimpleTypeDescription
 */
export interface SimpleTypeDescription {
    /**
     * 
     * @type {NodeId}
     * @memberof SimpleTypeDescription
     */
    BaseDataType?: NodeId;
    /**
     * 
     * @type {number}
     * @memberof SimpleTypeDescription
     */
    BuiltInType?: number;
    /**
     * 
     * @type {NodeId}
     * @memberof SimpleTypeDescription
     */
    DataTypeId?: NodeId;
    /**
     * 
     * @type {QualifiedName}
     * @memberof SimpleTypeDescription
     */
    Name?: QualifiedName;
}

/**
 * Check if a given object implements the SimpleTypeDescription interface.
 */
export function instanceOfSimpleTypeDescription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SimpleTypeDescriptionFromJSON(json: any): SimpleTypeDescription {
    return SimpleTypeDescriptionFromJSONTyped(json, false);
}

export function SimpleTypeDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleTypeDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'BaseDataType': !exists(json, 'BaseDataType') ? undefined : NodeIdFromJSON(json['BaseDataType']),
        'BuiltInType': !exists(json, 'BuiltInType') ? undefined : json['BuiltInType'],
        'DataTypeId': !exists(json, 'DataTypeId') ? undefined : NodeIdFromJSON(json['DataTypeId']),
        'Name': !exists(json, 'Name') ? undefined : QualifiedNameFromJSON(json['Name']),
    };
}

export function SimpleTypeDescriptionToJSON(value?: SimpleTypeDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'BaseDataType': NodeIdToJSON(value.BaseDataType),
        'BuiltInType': value.BuiltInType,
        'DataTypeId': NodeIdToJSON(value.DataTypeId),
        'Name': QualifiedNameToJSON(value.Name),
    };
}

