/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LocalizedText } from './LocalizedText';
import {
    LocalizedTextFromJSON,
    LocalizedTextFromJSONTyped,
    LocalizedTextToJSON,
} from './LocalizedText';
import type { NodeId } from './NodeId';
import {
    NodeIdFromJSON,
    NodeIdFromJSONTyped,
    NodeIdToJSON,
} from './NodeId';

/**
 * 
 * @export
 * @interface StructureField
 */
export interface StructureField {
    /**
     * 
     * @type {string}
     * @memberof StructureField
     */
    Name?: string;
    /**
     * 
     * @type {LocalizedText}
     * @memberof StructureField
     */
    Description?: LocalizedText;
    /**
     * 
     * @type {NodeId}
     * @memberof StructureField
     */
    DataType?: NodeId;
    /**
     * 
     * @type {number}
     * @memberof StructureField
     */
    ValueRank?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof StructureField
     */
    ArrayDimensions?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof StructureField
     */
    MaxStringLength?: number;
    /**
     * 
     * @type {boolean}
     * @memberof StructureField
     */
    IsOptional?: boolean;
}

/**
 * Check if a given object implements the StructureField interface.
 */
export function instanceOfStructureField(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructureFieldFromJSON(json: any): StructureField {
    return StructureFieldFromJSONTyped(json, false);
}

export function StructureFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructureField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Description': !exists(json, 'Description') ? undefined : LocalizedTextFromJSON(json['Description']),
        'DataType': !exists(json, 'DataType') ? undefined : NodeIdFromJSON(json['DataType']),
        'ValueRank': !exists(json, 'ValueRank') ? undefined : json['ValueRank'],
        'ArrayDimensions': !exists(json, 'ArrayDimensions') ? undefined : json['ArrayDimensions'],
        'MaxStringLength': !exists(json, 'MaxStringLength') ? undefined : json['MaxStringLength'],
        'IsOptional': !exists(json, 'IsOptional') ? undefined : json['IsOptional'],
    };
}

export function StructureFieldToJSON(value?: StructureField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.Name,
        'Description': LocalizedTextToJSON(value.Description),
        'DataType': NodeIdToJSON(value.DataType),
        'ValueRank': value.ValueRank,
        'ArrayDimensions': value.ArrayDimensions,
        'MaxStringLength': value.MaxStringLength,
        'IsOptional': value.IsOptional,
    };
}

