/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StructureType = {
    Structure: 0,
    StructureWithOptionalFields: 1,
    Union: 2,
    StructureWithSubtypedValues: 3,
    UnionWithSubtypedValues: 4
} as const;
export type StructureType = typeof StructureType[keyof typeof StructureType];


export function StructureTypeFromJSON(json: any): StructureType {
    return StructureTypeFromJSONTyped(json, false);
}

export function StructureTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructureType {
    return json as StructureType;
}

export function StructureTypeToJSON(value?: StructureType | null): any {
    return value as any;
}

