/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BrowsePath } from './BrowsePath';
import {
    BrowsePathFromJSON,
    BrowsePathFromJSONTyped,
    BrowsePathToJSON,
} from './BrowsePath';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';

/**
 * 
 * @export
 * @interface TranslateBrowsePathsToNodeIdsRequest
 */
export interface TranslateBrowsePathsToNodeIdsRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof TranslateBrowsePathsToNodeIdsRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<BrowsePath>}
     * @memberof TranslateBrowsePathsToNodeIdsRequest
     */
    BrowsePaths?: Array<BrowsePath>;
}

/**
 * Check if a given object implements the TranslateBrowsePathsToNodeIdsRequest interface.
 */
export function instanceOfTranslateBrowsePathsToNodeIdsRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TranslateBrowsePathsToNodeIdsRequestFromJSON(json: any): TranslateBrowsePathsToNodeIdsRequest {
    return TranslateBrowsePathsToNodeIdsRequestFromJSONTyped(json, false);
}

export function TranslateBrowsePathsToNodeIdsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslateBrowsePathsToNodeIdsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'BrowsePaths': !exists(json, 'BrowsePaths') ? undefined : ((json['BrowsePaths'] as Array<any>).map(BrowsePathFromJSON)),
    };
}

export function TranslateBrowsePathsToNodeIdsRequestToJSON(value?: TranslateBrowsePathsToNodeIdsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'BrowsePaths': value.BrowsePaths === undefined ? undefined : ((value.BrowsePaths as Array<any>).map(BrowsePathToJSON)),
    };
}

