/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserTokenType = {
    Anonymous: 0,
    UserName: 1,
    Certificate: 2,
    IssuedToken: 3
} as const;
export type UserTokenType = typeof UserTokenType[keyof typeof UserTokenType];


export function UserTokenTypeFromJSON(json: any): UserTokenType {
    return UserTokenTypeFromJSONTyped(json, false);
}

export function UserTokenTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTokenType {
    return json as UserTokenType;
}

export function UserTokenTypeToJSON(value?: UserTokenType | null): any {
    return value as any;
}

