/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NodeId } from './NodeId';
import {
    NodeIdFromJSON,
    NodeIdFromJSONTyped,
    NodeIdToJSON,
} from './NodeId';

/**
 * 
 * @export
 * @interface ViewDescription
 */
export interface ViewDescription {
    /**
     * 
     * @type {NodeId}
     * @memberof ViewDescription
     */
    ViewId?: NodeId;
    /**
     * 
     * @type {Date}
     * @memberof ViewDescription
     */
    Timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof ViewDescription
     */
    ViewVersion?: number;
}

/**
 * Check if a given object implements the ViewDescription interface.
 */
export function instanceOfViewDescription(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ViewDescriptionFromJSON(json: any): ViewDescription {
    return ViewDescriptionFromJSONTyped(json, false);
}

export function ViewDescriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewDescription {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ViewId': !exists(json, 'ViewId') ? undefined : NodeIdFromJSON(json['ViewId']),
        'Timestamp': !exists(json, 'Timestamp') ? undefined : (new Date(json['Timestamp'])),
        'ViewVersion': !exists(json, 'ViewVersion') ? undefined : json['ViewVersion'],
    };
}

export function ViewDescriptionToJSON(value?: ViewDescription | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ViewId': NodeIdToJSON(value.ViewId),
        'Timestamp': value.Timestamp === undefined ? undefined : (value.Timestamp.toISOString()),
        'ViewVersion': value.ViewVersion,
    };
}

