/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WriteResponse } from './WriteResponse';
import {
    WriteResponseFromJSON,
    WriteResponseFromJSONTyped,
    WriteResponseToJSON,
} from './WriteResponse';

/**
 * 
 * @export
 * @interface WriteResponseMessage
 */
export interface WriteResponseMessage {
    /**
     * 
     * @type {Array<string>}
     * @memberof WriteResponseMessage
     */
    NamespaceUris?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof WriteResponseMessage
     */
    ServerUris?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof WriteResponseMessage
     */
    ServiceId?: number;
    /**
     * 
     * @type {WriteResponse}
     * @memberof WriteResponseMessage
     */
    Body?: WriteResponse;
}

/**
 * Check if a given object implements the WriteResponseMessage interface.
 */
export function instanceOfWriteResponseMessage(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WriteResponseMessageFromJSON(json: any): WriteResponseMessage {
    return WriteResponseMessageFromJSONTyped(json, false);
}

export function WriteResponseMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteResponseMessage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'NamespaceUris': !exists(json, 'NamespaceUris') ? undefined : json['NamespaceUris'],
        'ServerUris': !exists(json, 'ServerUris') ? undefined : json['ServerUris'],
        'ServiceId': !exists(json, 'ServiceId') ? undefined : json['ServiceId'],
        'Body': !exists(json, 'Body') ? undefined : WriteResponseFromJSON(json['Body']),
    };
}

export function WriteResponseMessageToJSON(value?: WriteResponseMessage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NamespaceUris': value.NamespaceUris,
        'ServerUris': value.ServerUris,
        'ServiceId': value.ServiceId,
        'Body': WriteResponseToJSON(value.Body),
    };
}

