/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DataSetWriterDataType } from './DataSetWriterDataType';
import {
    DataSetWriterDataTypeFromJSON,
    DataSetWriterDataTypeFromJSONTyped,
    DataSetWriterDataTypeToJSON,
} from './DataSetWriterDataType';
import type { EndpointDescription } from './EndpointDescription';
import {
    EndpointDescriptionFromJSON,
    EndpointDescriptionFromJSONTyped,
    EndpointDescriptionToJSON,
} from './EndpointDescription';
import type { ExtensionObject } from './ExtensionObject';
import {
    ExtensionObjectFromJSON,
    ExtensionObjectFromJSONTyped,
    ExtensionObjectToJSON,
} from './ExtensionObject';
import type { KeyValuePair } from './KeyValuePair';
import {
    KeyValuePairFromJSON,
    KeyValuePairFromJSONTyped,
    KeyValuePairToJSON,
} from './KeyValuePair';

/**
 * 
 * @export
 * @interface WriterGroupDataType
 */
export interface WriterGroupDataType {
    /**
     * 
     * @type {number}
     * @memberof WriterGroupDataType
     */
    WriterGroupId?: number;
    /**
     * 
     * @type {number}
     * @memberof WriterGroupDataType
     */
    PublishingInterval?: number;
    /**
     * 
     * @type {number}
     * @memberof WriterGroupDataType
     */
    KeepAliveTime?: number;
    /**
     * 
     * @type {number}
     * @memberof WriterGroupDataType
     */
    Priority?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof WriterGroupDataType
     */
    LocaleIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof WriterGroupDataType
     */
    HeaderLayoutUri?: string;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof WriterGroupDataType
     */
    TransportSettings?: ExtensionObject;
    /**
     * 
     * @type {ExtensionObject}
     * @memberof WriterGroupDataType
     */
    MessageSettings?: ExtensionObject;
    /**
     * 
     * @type {Array<DataSetWriterDataType>}
     * @memberof WriterGroupDataType
     */
    DataSetWriters?: Array<DataSetWriterDataType>;
    /**
     * 
     * @type {string}
     * @memberof WriterGroupDataType
     */
    Name?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WriterGroupDataType
     */
    Enabled?: boolean;
    /**
     * 
     * @type {number}
     * @memberof WriterGroupDataType
     */
    SecurityMode?: number;
    /**
     * 
     * @type {string}
     * @memberof WriterGroupDataType
     */
    SecurityGroupId?: string;
    /**
     * 
     * @type {Array<EndpointDescription>}
     * @memberof WriterGroupDataType
     */
    SecurityKeyServices?: Array<EndpointDescription>;
    /**
     * 
     * @type {number}
     * @memberof WriterGroupDataType
     */
    MaxNetworkMessageSize?: number;
    /**
     * 
     * @type {Array<KeyValuePair>}
     * @memberof WriterGroupDataType
     */
    GroupProperties?: Array<KeyValuePair>;
}

/**
 * Check if a given object implements the WriterGroupDataType interface.
 */
export function instanceOfWriterGroupDataType(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WriterGroupDataTypeFromJSON(json: any): WriterGroupDataType {
    return WriterGroupDataTypeFromJSONTyped(json, false);
}

export function WriterGroupDataTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriterGroupDataType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'WriterGroupId': !exists(json, 'WriterGroupId') ? undefined : json['WriterGroupId'],
        'PublishingInterval': !exists(json, 'PublishingInterval') ? undefined : json['PublishingInterval'],
        'KeepAliveTime': !exists(json, 'KeepAliveTime') ? undefined : json['KeepAliveTime'],
        'Priority': !exists(json, 'Priority') ? undefined : json['Priority'],
        'LocaleIds': !exists(json, 'LocaleIds') ? undefined : json['LocaleIds'],
        'HeaderLayoutUri': !exists(json, 'HeaderLayoutUri') ? undefined : json['HeaderLayoutUri'],
        'TransportSettings': !exists(json, 'TransportSettings') ? undefined : ExtensionObjectFromJSON(json['TransportSettings']),
        'MessageSettings': !exists(json, 'MessageSettings') ? undefined : ExtensionObjectFromJSON(json['MessageSettings']),
        'DataSetWriters': !exists(json, 'DataSetWriters') ? undefined : ((json['DataSetWriters'] as Array<any>).map(DataSetWriterDataTypeFromJSON)),
        'Name': !exists(json, 'Name') ? undefined : json['Name'],
        'Enabled': !exists(json, 'Enabled') ? undefined : json['Enabled'],
        'SecurityMode': !exists(json, 'SecurityMode') ? undefined : json['SecurityMode'],
        'SecurityGroupId': !exists(json, 'SecurityGroupId') ? undefined : json['SecurityGroupId'],
        'SecurityKeyServices': !exists(json, 'SecurityKeyServices') ? undefined : ((json['SecurityKeyServices'] as Array<any>).map(EndpointDescriptionFromJSON)),
        'MaxNetworkMessageSize': !exists(json, 'MaxNetworkMessageSize') ? undefined : json['MaxNetworkMessageSize'],
        'GroupProperties': !exists(json, 'GroupProperties') ? undefined : ((json['GroupProperties'] as Array<any>).map(KeyValuePairFromJSON)),
    };
}

export function WriterGroupDataTypeToJSON(value?: WriterGroupDataType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'WriterGroupId': value.WriterGroupId,
        'PublishingInterval': value.PublishingInterval,
        'KeepAliveTime': value.KeepAliveTime,
        'Priority': value.Priority,
        'LocaleIds': value.LocaleIds,
        'HeaderLayoutUri': value.HeaderLayoutUri,
        'TransportSettings': ExtensionObjectToJSON(value.TransportSettings),
        'MessageSettings': ExtensionObjectToJSON(value.MessageSettings),
        'DataSetWriters': value.DataSetWriters === undefined ? undefined : ((value.DataSetWriters as Array<any>).map(DataSetWriterDataTypeToJSON)),
        'Name': value.Name,
        'Enabled': value.Enabled,
        'SecurityMode': value.SecurityMode,
        'SecurityGroupId': value.SecurityGroupId,
        'SecurityKeyServices': value.SecurityKeyServices === undefined ? undefined : ((value.SecurityKeyServices as Array<any>).map(EndpointDescriptionToJSON)),
        'MaxNetworkMessageSize': value.MaxNetworkMessageSize,
        'GroupProperties': value.GroupProperties === undefined ? undefined : ((value.GroupProperties as Array<any>).map(KeyValuePairToJSON)),
    };
}

