/* tslint:disable */
/* eslint-disable */
/**
 * OPC UA REST API
 * This API provides simple REST based access to an OPC UA server.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: office@opcfoundation.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { RequestHeader } from './RequestHeader';
import {
    RequestHeaderFromJSON,
    RequestHeaderFromJSONTyped,
    RequestHeaderToJSON,
} from './RequestHeader';
import type { WriteValue } from './WriteValue';
import {
    WriteValueFromJSON,
    WriteValueFromJSONTyped,
    WriteValueToJSON,
} from './WriteValue';

/**
 * 
 * @export
 * @interface WriteRequest
 */
export interface WriteRequest {
    /**
     * 
     * @type {RequestHeader}
     * @memberof WriteRequest
     */
    RequestHeader?: RequestHeader;
    /**
     * 
     * @type {Array<WriteValue>}
     * @memberof WriteRequest
     */
    NodesToWrite?: Array<WriteValue>;
}

/**
 * Check if a given object implements the WriteRequest interface.
 */
export function instanceOfWriteRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WriteRequestFromJSON(json: any): WriteRequest {
    return WriteRequestFromJSONTyped(json, false);
}

export function WriteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'RequestHeader': !exists(json, 'RequestHeader') ? undefined : RequestHeaderFromJSON(json['RequestHeader']),
        'NodesToWrite': !exists(json, 'NodesToWrite') ? undefined : ((json['NodesToWrite'] as Array<any>).map(WriteValueFromJSON)),
    };
}

export function WriteRequestToJSON(value?: WriteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RequestHeader': RequestHeaderToJSON(value.RequestHeader),
        'NodesToWrite': value.NodesToWrite === undefined ? undefined : ((value.NodesToWrite as Array<any>).map(WriteValueToJSON)),
    };
}

