export const NS = 'urn:opcua.org:2025-01:iiot-starterkit:boiler';

export class BrowseNames {
   static readonly Boiler_BinarySchema: string = 'Boiler'
   static readonly Boiler_XmlSchema: string = 'Boiler'
   static readonly Boiler1: string = 'Boiler #1'
   static readonly BoilerDrumType: string = 'BoilerDrumType'
   static readonly BoilerInputPipeType: string = 'BoilerInputPipeType'
   static readonly BoilerOutputPipeType: string = 'BoilerOutputPipeType'
   static readonly BoilerType: string = 'BoilerType'
   static readonly ChangeSetPoints: string = 'ChangeSetPoints'
   static readonly ChangeSetPointsRequest: string = 'ChangeSetPointsRequest'
   static readonly ChangeSetPointsResponse: string = 'ChangeSetPointsResponse'
   static readonly ControlOut: string = 'ControlOut'
   static readonly CustomController: string = 'CCX001'
   static readonly CustomControllerType: string = 'CustomControllerType'
   static readonly Drum: string = 'DrumX001'
   static readonly EmergencyShutdown: string = 'EmergencyShutdown'
   static readonly EnergyConsumption: string = 'EnergyConsumption'
   static readonly EnergyConsumptionType: string = 'EnergyConsumptionType'
   static readonly FlowController: string = 'FCX001'
   static readonly FlowControllerType: string = 'FlowControllerType'
   static readonly FlowTo: string = 'FlowTo'
   static readonly FlowTransmitter1: string = 'FTX001'
   static readonly FlowTransmitter2: string = 'FTX002'
   static readonly FlowTransmitterType: string = 'FlowTransmitterType'
   static readonly GenericActuatorType: string = 'GenericActuatorType'
   static readonly GenericControllerType: string = 'GenericControllerType'
   static readonly GenericSensorType: string = 'GenericSensorType'
   static readonly Input: string = 'Input'
   static readonly Input1: string = 'Input1'
   static readonly Input2: string = 'Input2'
   static readonly Input3: string = 'Input3'
   static readonly InputPipe: string = 'PipeX001'
   static readonly LevelController: string = 'LCX001'
   static readonly LevelControllerType: string = 'LevelControllerType'
   static readonly LevelIndicator: string = 'LIX001'
   static readonly LevelIndicatorType: string = 'LevelIndicatorType'
   static readonly Measurement: string = 'Measurement'
   static readonly Output: string = 'Output'
   static readonly OutputPipe: string = 'PipeX002'
   static readonly Restart: string = 'Restart'
   static readonly SetPoint: string = 'SetPoint'
   static readonly SetPointMask: string = 'SetPointMask'
   static readonly SignalTo: string = 'SignalTo'
   static readonly Valve: string = 'ValveX001'
   static readonly ValveType: string = 'ValveType'
}

export class DataTypeIds {
    static readonly EnergyConsumptionType: string = 'nsu=' + NS + ';i=27'
    static readonly SetPointMask: string = 'nsu=' + NS + ';i=218'
    static readonly ChangeSetPointsRequest: string = 'nsu=' + NS + ';i=220'
    static readonly ChangeSetPointsResponse: string = 'nsu=' + NS + ';i=221'
}

export class MethodIds {
    static readonly BoilerType_ChangeSetPoints: string = 'nsu=' + NS + ';i=200'
    static readonly BoilerType_EmergencyShutdown: string = 'nsu=' + NS + ';i=203'
    static readonly BoilerType_Restart: string = 'nsu=' + NS + ';i=206'
    static readonly Boiler1_ChangeSetPoints: string = 'nsu=' + NS + ';i=209'
    static readonly Boiler1_EmergencyShutdown: string = 'nsu=' + NS + ';i=212'
    static readonly Boiler1_Restart: string = 'nsu=' + NS + ';i=215'
}

export class ObjectIds {
    static readonly BoilerInputPipeType_FlowTransmitter1: string = 'nsu=' + NS + ';i=74'
    static readonly BoilerInputPipeType_Valve: string = 'nsu=' + NS + ';i=81'
    static readonly BoilerDrumType_LevelIndicator: string = 'nsu=' + NS + ';i=89'
    static readonly BoilerOutputPipeType_FlowTransmitter2: string = 'nsu=' + NS + ';i=97'
    static readonly BoilerType_InputPipe: string = 'nsu=' + NS + ';i=56'
    static readonly BoilerType_InputPipe_FlowTransmitter1: string = 'nsu=' + NS + ';i=104'
    static readonly BoilerType_InputPipe_Valve: string = 'nsu=' + NS + ';i=111'
    static readonly BoilerType_Drum: string = 'nsu=' + NS + ';i=57'
    static readonly BoilerType_Drum_LevelIndicator: string = 'nsu=' + NS + ';i=58'
    static readonly BoilerType_OutputPipe: string = 'nsu=' + NS + ';i=65'
    static readonly BoilerType_OutputPipe_FlowTransmitter2: string = 'nsu=' + NS + ';i=118'
    static readonly BoilerType_FlowController: string = 'nsu=' + NS + ';i=125'
    static readonly BoilerType_LevelController: string = 'nsu=' + NS + ';i=129'
    static readonly BoilerType_CustomController: string = 'nsu=' + NS + ';i=133'
    static readonly Boiler1: string = 'nsu=' + NS + ';i=138'
    static readonly Boiler1_InputPipe: string = 'nsu=' + NS + ';i=139'
    static readonly Boiler1_InputPipe_FlowTransmitter1: string = 'nsu=' + NS + ';i=140'
    static readonly Boiler1_InputPipe_Valve: string = 'nsu=' + NS + ';i=147'
    static readonly Boiler1_Drum: string = 'nsu=' + NS + ';i=154'
    static readonly Boiler1_Drum_LevelIndicator: string = 'nsu=' + NS + ';i=155'
    static readonly Boiler1_OutputPipe: string = 'nsu=' + NS + ';i=162'
    static readonly Boiler1_OutputPipe_FlowTransmitter2: string = 'nsu=' + NS + ';i=163'
    static readonly Boiler1_FlowController: string = 'nsu=' + NS + ';i=170'
    static readonly Boiler1_LevelController: string = 'nsu=' + NS + ';i=174'
    static readonly Boiler1_CustomController: string = 'nsu=' + NS + ';i=178'
    static readonly EnergyConsumptionType_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=241'
    static readonly ChangeSetPointsRequest_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=222'
    static readonly ChangeSetPointsResponse_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=223'
    static readonly EnergyConsumptionType_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=245'
    static readonly ChangeSetPointsRequest_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=230'
    static readonly ChangeSetPointsResponse_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=231'
    static readonly EnergyConsumptionType_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=249'
    static readonly ChangeSetPointsRequest_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=238'
    static readonly ChangeSetPointsResponse_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=239'
}

export class ObjectTypeIds {
    static readonly GenericControllerType: string = 'nsu=' + NS + ';i=3'
    static readonly GenericSensorType: string = 'nsu=' + NS + ';i=7'
    static readonly GenericActuatorType: string = 'nsu=' + NS + ';i=14'
    static readonly CustomControllerType: string = 'nsu=' + NS + ';i=21'
    static readonly ValveType: string = 'nsu=' + NS + ';i=26'
    static readonly LevelControllerType: string = 'nsu=' + NS + ';i=33'
    static readonly FlowControllerType: string = 'nsu=' + NS + ';i=37'
    static readonly LevelIndicatorType: string = 'nsu=' + NS + ';i=41'
    static readonly FlowTransmitterType: string = 'nsu=' + NS + ';i=48'
    static readonly BoilerInputPipeType: string = 'nsu=' + NS + ';i=73'
    static readonly BoilerDrumType: string = 'nsu=' + NS + ';i=88'
    static readonly BoilerOutputPipeType: string = 'nsu=' + NS + ';i=96'
    static readonly BoilerType: string = 'nsu=' + NS + ';i=55'
}

export class ReferenceTypeIds {
    static readonly FlowTo: string = 'nsu=' + NS + ';i=1'
    static readonly SignalTo: string = 'nsu=' + NS + ';i=2'
}

export class VariableIds {
    static readonly GenericControllerType_Measurement: string = 'nsu=' + NS + ';i=4'
    static readonly GenericControllerType_SetPoint: string = 'nsu=' + NS + ';i=5'
    static readonly GenericControllerType_ControlOut: string = 'nsu=' + NS + ';i=6'
    static readonly GenericSensorType_Output: string = 'nsu=' + NS + ';i=8'
    static readonly GenericSensorType_Output_EURange: string = 'nsu=' + NS + ';i=11'
    static readonly GenericSensorType_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=13'
    static readonly GenericActuatorType_Input: string = 'nsu=' + NS + ';i=15'
    static readonly GenericActuatorType_Input_EURange: string = 'nsu=' + NS + ';i=18'
    static readonly GenericActuatorType_EnergyConsumption: string = 'nsu=' + NS + ';i=28'
    static readonly GenericActuatorType_EnergyConsumption_EngineeringUnits: string = 'nsu=' + NS + ';i=34'
    static readonly CustomControllerType_Input1: string = 'nsu=' + NS + ';i=22'
    static readonly CustomControllerType_Input2: string = 'nsu=' + NS + ';i=23'
    static readonly CustomControllerType_Input3: string = 'nsu=' + NS + ';i=24'
    static readonly CustomControllerType_ControlOut: string = 'nsu=' + NS + ';i=25'
    static readonly BoilerInputPipeType_FlowTransmitter1_Output: string = 'nsu=' + NS + ';i=75'
    static readonly BoilerInputPipeType_FlowTransmitter1_Output_EURange: string = 'nsu=' + NS + ';i=78'
    static readonly BoilerInputPipeType_FlowTransmitter1_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=80'
    static readonly BoilerInputPipeType_Valve_Input: string = 'nsu=' + NS + ';i=82'
    static readonly BoilerInputPipeType_Valve_Input_EURange: string = 'nsu=' + NS + ';i=85'
    static readonly BoilerInputPipeType_Valve_EnergyConsumption: string = 'nsu=' + NS + ';i=35'
    static readonly BoilerInputPipeType_Valve_EnergyConsumption_EngineeringUnits: string = 'nsu=' + NS + ';i=42'
    static readonly BoilerDrumType_LevelIndicator_Output: string = 'nsu=' + NS + ';i=90'
    static readonly BoilerDrumType_LevelIndicator_Output_EURange: string = 'nsu=' + NS + ';i=93'
    static readonly BoilerDrumType_LevelIndicator_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=95'
    static readonly BoilerOutputPipeType_FlowTransmitter2_Output: string = 'nsu=' + NS + ';i=98'
    static readonly BoilerOutputPipeType_FlowTransmitter2_Output_EURange: string = 'nsu=' + NS + ';i=101'
    static readonly BoilerOutputPipeType_FlowTransmitter2_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=103'
    static readonly SetPointMask_OptionSetValues: string = 'nsu=' + NS + ';i=219'
    static readonly BoilerType_InputPipe_FlowTransmitter1_Output: string = 'nsu=' + NS + ';i=105'
    static readonly BoilerType_InputPipe_FlowTransmitter1_Output_EURange: string = 'nsu=' + NS + ';i=108'
    static readonly BoilerType_InputPipe_FlowTransmitter1_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=110'
    static readonly BoilerType_InputPipe_Valve_Input: string = 'nsu=' + NS + ';i=112'
    static readonly BoilerType_InputPipe_Valve_Input_EURange: string = 'nsu=' + NS + ';i=115'
    static readonly BoilerType_InputPipe_Valve_EnergyConsumption: string = 'nsu=' + NS + ';i=43'
    static readonly BoilerType_InputPipe_Valve_EnergyConsumption_EngineeringUnits: string = 'nsu=' + NS + ';i=49'
    static readonly BoilerType_Drum_LevelIndicator_Output: string = 'nsu=' + NS + ';i=59'
    static readonly BoilerType_Drum_LevelIndicator_Output_EURange: string = 'nsu=' + NS + ';i=62'
    static readonly BoilerType_Drum_LevelIndicator_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=64'
    static readonly BoilerType_OutputPipe_FlowTransmitter2_Output: string = 'nsu=' + NS + ';i=119'
    static readonly BoilerType_OutputPipe_FlowTransmitter2_Output_EURange: string = 'nsu=' + NS + ';i=122'
    static readonly BoilerType_OutputPipe_FlowTransmitter2_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=124'
    static readonly BoilerType_FlowController_Measurement: string = 'nsu=' + NS + ';i=126'
    static readonly BoilerType_FlowController_SetPoint: string = 'nsu=' + NS + ';i=127'
    static readonly BoilerType_FlowController_ControlOut: string = 'nsu=' + NS + ';i=128'
    static readonly BoilerType_LevelController_Measurement: string = 'nsu=' + NS + ';i=130'
    static readonly BoilerType_LevelController_SetPoint: string = 'nsu=' + NS + ';i=131'
    static readonly BoilerType_LevelController_ControlOut: string = 'nsu=' + NS + ';i=132'
    static readonly BoilerType_CustomController_Input1: string = 'nsu=' + NS + ';i=134'
    static readonly BoilerType_CustomController_Input2: string = 'nsu=' + NS + ';i=135'
    static readonly BoilerType_CustomController_Input3: string = 'nsu=' + NS + ';i=136'
    static readonly BoilerType_CustomController_ControlOut: string = 'nsu=' + NS + ';i=137'
    static readonly BoilerType_ChangeSetPoints_InputArguments: string = 'nsu=' + NS + ';i=201'
    static readonly BoilerType_ChangeSetPoints_OutputArguments: string = 'nsu=' + NS + ';i=202'
    static readonly BoilerType_EmergencyShutdown_InputArguments: string = 'nsu=' + NS + ';i=204'
    static readonly BoilerType_EmergencyShutdown_OutputArguments: string = 'nsu=' + NS + ';i=205'
    static readonly BoilerType_Restart_InputArguments: string = 'nsu=' + NS + ';i=207'
    static readonly BoilerType_Restart_OutputArguments: string = 'nsu=' + NS + ';i=208'
    static readonly Boiler1_InputPipe_FlowTransmitter1_Output: string = 'nsu=' + NS + ';i=141'
    static readonly Boiler1_InputPipe_FlowTransmitter1_Output_EURange: string = 'nsu=' + NS + ';i=144'
    static readonly Boiler1_InputPipe_FlowTransmitter1_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=146'
    static readonly Boiler1_InputPipe_Valve_Input: string = 'nsu=' + NS + ';i=148'
    static readonly Boiler1_InputPipe_Valve_Input_EURange: string = 'nsu=' + NS + ';i=151'
    static readonly Boiler1_InputPipe_Valve_EnergyConsumption: string = 'nsu=' + NS + ';i=50'
    static readonly Boiler1_InputPipe_Valve_EnergyConsumption_EngineeringUnits: string = 'nsu=' + NS + ';i=240'
    static readonly Boiler1_Drum_LevelIndicator_Output: string = 'nsu=' + NS + ';i=156'
    static readonly Boiler1_Drum_LevelIndicator_Output_EURange: string = 'nsu=' + NS + ';i=159'
    static readonly Boiler1_Drum_LevelIndicator_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=161'
    static readonly Boiler1_OutputPipe_FlowTransmitter2_Output: string = 'nsu=' + NS + ';i=164'
    static readonly Boiler1_OutputPipe_FlowTransmitter2_Output_EURange: string = 'nsu=' + NS + ';i=167'
    static readonly Boiler1_OutputPipe_FlowTransmitter2_Output_EngineeringUnits: string = 'nsu=' + NS + ';i=169'
    static readonly Boiler1_FlowController_Measurement: string = 'nsu=' + NS + ';i=171'
    static readonly Boiler1_FlowController_SetPoint: string = 'nsu=' + NS + ';i=172'
    static readonly Boiler1_FlowController_ControlOut: string = 'nsu=' + NS + ';i=173'
    static readonly Boiler1_LevelController_Measurement: string = 'nsu=' + NS + ';i=175'
    static readonly Boiler1_LevelController_SetPoint: string = 'nsu=' + NS + ';i=176'
    static readonly Boiler1_LevelController_ControlOut: string = 'nsu=' + NS + ';i=177'
    static readonly Boiler1_CustomController_Input1: string = 'nsu=' + NS + ';i=179'
    static readonly Boiler1_CustomController_Input2: string = 'nsu=' + NS + ';i=180'
    static readonly Boiler1_CustomController_Input3: string = 'nsu=' + NS + ';i=181'
    static readonly Boiler1_CustomController_ControlOut: string = 'nsu=' + NS + ';i=182'
    static readonly Boiler1_ChangeSetPoints_InputArguments: string = 'nsu=' + NS + ';i=210'
    static readonly Boiler1_ChangeSetPoints_OutputArguments: string = 'nsu=' + NS + ';i=211'
    static readonly Boiler1_EmergencyShutdown_InputArguments: string = 'nsu=' + NS + ';i=213'
    static readonly Boiler1_EmergencyShutdown_OutputArguments: string = 'nsu=' + NS + ';i=214'
    static readonly Boiler1_Restart_InputArguments: string = 'nsu=' + NS + ';i=216'
    static readonly Boiler1_Restart_OutputArguments: string = 'nsu=' + NS + ';i=217'
    static readonly Boiler_BinarySchema: string = 'nsu=' + NS + ';i=192'
    static readonly Boiler_BinarySchema_NamespaceUri: string = 'nsu=' + NS + ';i=194'
    static readonly Boiler_BinarySchema_Deprecated: string = 'nsu=' + NS + ';i=15001'
    static readonly Boiler_BinarySchema_EnergyConsumptionType: string = 'nsu=' + NS + ';i=242'
    static readonly Boiler_BinarySchema_ChangeSetPointsRequest: string = 'nsu=' + NS + ';i=224'
    static readonly Boiler_BinarySchema_ChangeSetPointsResponse: string = 'nsu=' + NS + ';i=227'
    static readonly Boiler_XmlSchema: string = 'nsu=' + NS + ';i=185'
    static readonly Boiler_XmlSchema_NamespaceUri: string = 'nsu=' + NS + ';i=187'
    static readonly Boiler_XmlSchema_Deprecated: string = 'nsu=' + NS + ';i=15002'
    static readonly Boiler_XmlSchema_EnergyConsumptionType: string = 'nsu=' + NS + ';i=246'
    static readonly Boiler_XmlSchema_ChangeSetPointsRequest: string = 'nsu=' + NS + ';i=232'
    static readonly Boiler_XmlSchema_ChangeSetPointsResponse: string = 'nsu=' + NS + ';i=235'
}
