export const NS = 'urn:opcfoundation.org:2024-01:TestModel';

export class BrowseNames {
   static readonly AbstractStructure: string = 'AbstractStructure'
   static readonly ArrayStructure: string = 'ArrayStructure'
   static readonly ArrayStructureWithAllowSubtypes: string = 'ArrayStructureWithAllowSubtypes'
   static readonly BasicUnion: string = 'BasicUnion'
   static readonly ConcreteStructure: string = 'ConcreteStructure'
   static readonly EnumerationWithGaps: string = 'EnumerationWithGaps'
   static readonly NestedStructure: string = 'NestedStructure'
   static readonly NestedStructureWithAllowSubtypes: string = 'NestedStructureWithAllowSubtypes'
   static readonly ScalarStructure: string = 'ScalarStructure'
   static readonly ScalarStructureWithAllowSubtypes: string = 'ScalarStructureWithAllowSubtypes'
   static readonly StructureWithOptionalFields: string = 'StructureWithOptionalFields'
   static readonly TestModel_BinarySchema: string = 'TestModel'
   static readonly TestModel_XmlSchema: string = 'TestModel'
}

export class DataTypeIds {
    static readonly AbstractStructure: string = 'nsu=' + NS + ';i=61'
    static readonly ConcreteStructure: string = 'nsu=' + NS + ';i=62'
    static readonly EnumerationWithGaps: string = 'nsu=' + NS + ';i=63'
    static readonly ScalarStructure: string = 'nsu=' + NS + ';i=65'
    static readonly ScalarStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=66'
    static readonly ArrayStructure: string = 'nsu=' + NS + ';i=67'
    static readonly ArrayStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=68'
    static readonly NestedStructure: string = 'nsu=' + NS + ';i=69'
    static readonly NestedStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=70'
    static readonly BasicUnion: string = 'nsu=' + NS + ';i=143'
    static readonly StructureWithOptionalFields: string = 'nsu=' + NS + ';i=144'
}

export class ObjectIds {
    static readonly AbstractStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=71'
    static readonly ConcreteStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=72'
    static readonly ScalarStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=73'
    static readonly ScalarStructureWithAllowSubtypes_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=74'
    static readonly ArrayStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=75'
    static readonly ArrayStructureWithAllowSubtypes_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=76'
    static readonly NestedStructure_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=77'
    static readonly NestedStructureWithAllowSubtypes_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=78'
    static readonly BasicUnion_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=145'
    static readonly StructureWithOptionalFields_Encoding_DefaultBinary: string = 'nsu=' + NS + ';i=146'
    static readonly AbstractStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=103'
    static readonly ConcreteStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=104'
    static readonly ScalarStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=105'
    static readonly ScalarStructureWithAllowSubtypes_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=106'
    static readonly ArrayStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=107'
    static readonly ArrayStructureWithAllowSubtypes_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=108'
    static readonly NestedStructure_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=109'
    static readonly NestedStructureWithAllowSubtypes_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=110'
    static readonly BasicUnion_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=153'
    static readonly StructureWithOptionalFields_Encoding_DefaultXml: string = 'nsu=' + NS + ';i=154'
    static readonly AbstractStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=135'
    static readonly ConcreteStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=136'
    static readonly ScalarStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=137'
    static readonly ScalarStructureWithAllowSubtypes_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=138'
    static readonly ArrayStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=139'
    static readonly ArrayStructureWithAllowSubtypes_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=140'
    static readonly NestedStructure_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=141'
    static readonly NestedStructureWithAllowSubtypes_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=142'
    static readonly BasicUnion_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=161'
    static readonly StructureWithOptionalFields_Encoding_DefaultJson: string = 'nsu=' + NS + ';i=162'
}

export class VariableIds {
    static readonly EnumerationWithGaps_EnumValues: string = 'nsu=' + NS + ';i=64'
    static readonly TestModel_BinarySchema: string = 'nsu=' + NS + ';i=13'
    static readonly TestModel_BinarySchema_NamespaceUri: string = 'nsu=' + NS + ';i=15'
    static readonly TestModel_BinarySchema_Deprecated: string = 'nsu=' + NS + ';i=16'
    static readonly TestModel_BinarySchema_AbstractStructure: string = 'nsu=' + NS + ';i=79'
    static readonly TestModel_BinarySchema_ConcreteStructure: string = 'nsu=' + NS + ';i=82'
    static readonly TestModel_BinarySchema_ScalarStructure: string = 'nsu=' + NS + ';i=85'
    static readonly TestModel_BinarySchema_ScalarStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=88'
    static readonly TestModel_BinarySchema_ArrayStructure: string = 'nsu=' + NS + ';i=91'
    static readonly TestModel_BinarySchema_ArrayStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=94'
    static readonly TestModel_BinarySchema_NestedStructure: string = 'nsu=' + NS + ';i=97'
    static readonly TestModel_BinarySchema_NestedStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=100'
    static readonly TestModel_BinarySchema_BasicUnion: string = 'nsu=' + NS + ';i=147'
    static readonly TestModel_BinarySchema_StructureWithOptionalFields: string = 'nsu=' + NS + ';i=150'
    static readonly TestModel_XmlSchema: string = 'nsu=' + NS + ';i=37'
    static readonly TestModel_XmlSchema_NamespaceUri: string = 'nsu=' + NS + ';i=39'
    static readonly TestModel_XmlSchema_Deprecated: string = 'nsu=' + NS + ';i=40'
    static readonly TestModel_XmlSchema_AbstractStructure: string = 'nsu=' + NS + ';i=111'
    static readonly TestModel_XmlSchema_ConcreteStructure: string = 'nsu=' + NS + ';i=114'
    static readonly TestModel_XmlSchema_ScalarStructure: string = 'nsu=' + NS + ';i=117'
    static readonly TestModel_XmlSchema_ScalarStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=120'
    static readonly TestModel_XmlSchema_ArrayStructure: string = 'nsu=' + NS + ';i=123'
    static readonly TestModel_XmlSchema_ArrayStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=126'
    static readonly TestModel_XmlSchema_NestedStructure: string = 'nsu=' + NS + ';i=129'
    static readonly TestModel_XmlSchema_NestedStructureWithAllowSubtypes: string = 'nsu=' + NS + ';i=132'
    static readonly TestModel_XmlSchema_BasicUnion: string = 'nsu=' + NS + ';i=155'
    static readonly TestModel_XmlSchema_StructureWithOptionalFields: string = 'nsu=' + NS + ';i=158'
}
