export const NS = 'urn:opcua.org:2025-01:iiot-starterkit:boiler';

export const BrowseNames = Object.freeze({
   Boiler_BinarySchema: 'Boiler',
   Boiler_XmlSchema: 'Boiler',
   Boiler1: 'Boiler #1',
   BoilerDrumType: 'BoilerDrumType',
   BoilerInputPipeType: 'BoilerInputPipeType',
   BoilerOutputPipeType: 'BoilerOutputPipeType',
   BoilerType: 'BoilerType',
   ChangeSetPoints: 'ChangeSetPoints',
   ChangeSetPointsRequest: 'ChangeSetPointsRequest',
   ChangeSetPointsResponse: 'ChangeSetPointsResponse',
   ControlOut: 'ControlOut',
   CustomController: 'CCX001',
   CustomControllerType: 'CustomControllerType',
   Drum: 'DrumX001',
   EmergencyShutdown: 'EmergencyShutdown',
   EnergyConsumption: 'EnergyConsumption',
   EnergyConsumptionType: 'EnergyConsumptionType',
   FlowController: 'FCX001',
   FlowControllerType: 'FlowControllerType',
   FlowTo: 'FlowTo',
   FlowTransmitter1: 'FTX001',
   FlowTransmitter2: 'FTX002',
   FlowTransmitterType: 'FlowTransmitterType',
   GenericActuatorType: 'GenericActuatorType',
   GenericControllerType: 'GenericControllerType',
   GenericSensorType: 'GenericSensorType',
   Input: 'Input',
   Input1: 'Input1',
   Input2: 'Input2',
   Input3: 'Input3',
   InputPipe: 'PipeX001',
   LevelController: 'LCX001',
   LevelControllerType: 'LevelControllerType',
   LevelIndicator: 'LIX001',
   LevelIndicatorType: 'LevelIndicatorType',
   Measurement: 'Measurement',
   Output: 'Output',
   OutputPipe: 'PipeX002',
   Restart: 'Restart',
   SetPoint: 'SetPoint',
   SetPointMask: 'SetPointMask',
   SignalTo: 'SignalTo',
   Valve: 'ValveX001',
   ValveType: 'ValveType',
});

export const DataTypeIds = Object.freeze({
   EnergyConsumptionType: 'nsu=' + NS + ';i=27',
   SetPointMask: 'nsu=' + NS + ';i=218',
   ChangeSetPointsRequest: 'nsu=' + NS + ';i=220',
   ChangeSetPointsResponse: 'nsu=' + NS + ';i=221',
});

export const MethodIds = Object.freeze({
   BoilerType_ChangeSetPoints: 'nsu=' + NS + ';i=200',
   BoilerType_EmergencyShutdown: 'nsu=' + NS + ';i=203',
   BoilerType_Restart: 'nsu=' + NS + ';i=206',
   Boiler1_ChangeSetPoints: 'nsu=' + NS + ';i=209',
   Boiler1_EmergencyShutdown: 'nsu=' + NS + ';i=212',
   Boiler1_Restart: 'nsu=' + NS + ';i=215',
});

export const ObjectIds = Object.freeze({
   BoilerInputPipeType_FlowTransmitter1: 'nsu=' + NS + ';i=74',
   BoilerInputPipeType_Valve: 'nsu=' + NS + ';i=81',
   BoilerDrumType_LevelIndicator: 'nsu=' + NS + ';i=89',
   BoilerOutputPipeType_FlowTransmitter2: 'nsu=' + NS + ';i=97',
   BoilerType_InputPipe: 'nsu=' + NS + ';i=56',
   BoilerType_InputPipe_FlowTransmitter1: 'nsu=' + NS + ';i=104',
   BoilerType_InputPipe_Valve: 'nsu=' + NS + ';i=111',
   BoilerType_Drum: 'nsu=' + NS + ';i=57',
   BoilerType_Drum_LevelIndicator: 'nsu=' + NS + ';i=58',
   BoilerType_OutputPipe: 'nsu=' + NS + ';i=65',
   BoilerType_OutputPipe_FlowTransmitter2: 'nsu=' + NS + ';i=118',
   BoilerType_FlowController: 'nsu=' + NS + ';i=125',
   BoilerType_LevelController: 'nsu=' + NS + ';i=129',
   BoilerType_CustomController: 'nsu=' + NS + ';i=133',
   Boiler1: 'nsu=' + NS + ';i=138',
   Boiler1_InputPipe: 'nsu=' + NS + ';i=139',
   Boiler1_InputPipe_FlowTransmitter1: 'nsu=' + NS + ';i=140',
   Boiler1_InputPipe_Valve: 'nsu=' + NS + ';i=147',
   Boiler1_Drum: 'nsu=' + NS + ';i=154',
   Boiler1_Drum_LevelIndicator: 'nsu=' + NS + ';i=155',
   Boiler1_OutputPipe: 'nsu=' + NS + ';i=162',
   Boiler1_OutputPipe_FlowTransmitter2: 'nsu=' + NS + ';i=163',
   Boiler1_FlowController: 'nsu=' + NS + ';i=170',
   Boiler1_LevelController: 'nsu=' + NS + ';i=174',
   Boiler1_CustomController: 'nsu=' + NS + ';i=178',
   EnergyConsumptionType_Encoding_DefaultBinary: 'nsu=' + NS + ';i=241',
   ChangeSetPointsRequest_Encoding_DefaultBinary: 'nsu=' + NS + ';i=222',
   ChangeSetPointsResponse_Encoding_DefaultBinary: 'nsu=' + NS + ';i=223',
   EnergyConsumptionType_Encoding_DefaultXml: 'nsu=' + NS + ';i=245',
   ChangeSetPointsRequest_Encoding_DefaultXml: 'nsu=' + NS + ';i=230',
   ChangeSetPointsResponse_Encoding_DefaultXml: 'nsu=' + NS + ';i=231',
   EnergyConsumptionType_Encoding_DefaultJson: 'nsu=' + NS + ';i=249',
   ChangeSetPointsRequest_Encoding_DefaultJson: 'nsu=' + NS + ';i=238',
   ChangeSetPointsResponse_Encoding_DefaultJson: 'nsu=' + NS + ';i=239',
});

export const ObjectTypeIds = Object.freeze({
   GenericControllerType: 'nsu=' + NS + ';i=3',
   GenericSensorType: 'nsu=' + NS + ';i=7',
   GenericActuatorType: 'nsu=' + NS + ';i=14',
   CustomControllerType: 'nsu=' + NS + ';i=21',
   ValveType: 'nsu=' + NS + ';i=26',
   LevelControllerType: 'nsu=' + NS + ';i=33',
   FlowControllerType: 'nsu=' + NS + ';i=37',
   LevelIndicatorType: 'nsu=' + NS + ';i=41',
   FlowTransmitterType: 'nsu=' + NS + ';i=48',
   BoilerInputPipeType: 'nsu=' + NS + ';i=73',
   BoilerDrumType: 'nsu=' + NS + ';i=88',
   BoilerOutputPipeType: 'nsu=' + NS + ';i=96',
   BoilerType: 'nsu=' + NS + ';i=55',
});

export const ReferenceTypeIds = Object.freeze({
   FlowTo: 'nsu=' + NS + ';i=1',
   SignalTo: 'nsu=' + NS + ';i=2',
});

export const VariableIds = Object.freeze({
   GenericControllerType_Measurement: 'nsu=' + NS + ';i=4',
   GenericControllerType_SetPoint: 'nsu=' + NS + ';i=5',
   GenericControllerType_ControlOut: 'nsu=' + NS + ';i=6',
   GenericSensorType_Output: 'nsu=' + NS + ';i=8',
   GenericSensorType_Output_EURange: 'nsu=' + NS + ';i=11',
   GenericSensorType_Output_EngineeringUnits: 'nsu=' + NS + ';i=13',
   GenericActuatorType_Input: 'nsu=' + NS + ';i=15',
   GenericActuatorType_Input_EURange: 'nsu=' + NS + ';i=18',
   GenericActuatorType_EnergyConsumption: 'nsu=' + NS + ';i=28',
   GenericActuatorType_EnergyConsumption_EngineeringUnits: 'nsu=' + NS + ';i=34',
   CustomControllerType_Input1: 'nsu=' + NS + ';i=22',
   CustomControllerType_Input2: 'nsu=' + NS + ';i=23',
   CustomControllerType_Input3: 'nsu=' + NS + ';i=24',
   CustomControllerType_ControlOut: 'nsu=' + NS + ';i=25',
   BoilerInputPipeType_FlowTransmitter1_Output: 'nsu=' + NS + ';i=75',
   BoilerInputPipeType_FlowTransmitter1_Output_EURange: 'nsu=' + NS + ';i=78',
   BoilerInputPipeType_FlowTransmitter1_Output_EngineeringUnits: 'nsu=' + NS + ';i=80',
   BoilerInputPipeType_Valve_Input: 'nsu=' + NS + ';i=82',
   BoilerInputPipeType_Valve_Input_EURange: 'nsu=' + NS + ';i=85',
   BoilerInputPipeType_Valve_EnergyConsumption: 'nsu=' + NS + ';i=35',
   BoilerInputPipeType_Valve_EnergyConsumption_EngineeringUnits: 'nsu=' + NS + ';i=42',
   BoilerDrumType_LevelIndicator_Output: 'nsu=' + NS + ';i=90',
   BoilerDrumType_LevelIndicator_Output_EURange: 'nsu=' + NS + ';i=93',
   BoilerDrumType_LevelIndicator_Output_EngineeringUnits: 'nsu=' + NS + ';i=95',
   BoilerOutputPipeType_FlowTransmitter2_Output: 'nsu=' + NS + ';i=98',
   BoilerOutputPipeType_FlowTransmitter2_Output_EURange: 'nsu=' + NS + ';i=101',
   BoilerOutputPipeType_FlowTransmitter2_Output_EngineeringUnits: 'nsu=' + NS + ';i=103',
   SetPointMask_OptionSetValues: 'nsu=' + NS + ';i=219',
   BoilerType_InputPipe_FlowTransmitter1_Output: 'nsu=' + NS + ';i=105',
   BoilerType_InputPipe_FlowTransmitter1_Output_EURange: 'nsu=' + NS + ';i=108',
   BoilerType_InputPipe_FlowTransmitter1_Output_EngineeringUnits: 'nsu=' + NS + ';i=110',
   BoilerType_InputPipe_Valve_Input: 'nsu=' + NS + ';i=112',
   BoilerType_InputPipe_Valve_Input_EURange: 'nsu=' + NS + ';i=115',
   BoilerType_InputPipe_Valve_EnergyConsumption: 'nsu=' + NS + ';i=43',
   BoilerType_InputPipe_Valve_EnergyConsumption_EngineeringUnits: 'nsu=' + NS + ';i=49',
   BoilerType_Drum_LevelIndicator_Output: 'nsu=' + NS + ';i=59',
   BoilerType_Drum_LevelIndicator_Output_EURange: 'nsu=' + NS + ';i=62',
   BoilerType_Drum_LevelIndicator_Output_EngineeringUnits: 'nsu=' + NS + ';i=64',
   BoilerType_OutputPipe_FlowTransmitter2_Output: 'nsu=' + NS + ';i=119',
   BoilerType_OutputPipe_FlowTransmitter2_Output_EURange: 'nsu=' + NS + ';i=122',
   BoilerType_OutputPipe_FlowTransmitter2_Output_EngineeringUnits: 'nsu=' + NS + ';i=124',
   BoilerType_FlowController_Measurement: 'nsu=' + NS + ';i=126',
   BoilerType_FlowController_SetPoint: 'nsu=' + NS + ';i=127',
   BoilerType_FlowController_ControlOut: 'nsu=' + NS + ';i=128',
   BoilerType_LevelController_Measurement: 'nsu=' + NS + ';i=130',
   BoilerType_LevelController_SetPoint: 'nsu=' + NS + ';i=131',
   BoilerType_LevelController_ControlOut: 'nsu=' + NS + ';i=132',
   BoilerType_CustomController_Input1: 'nsu=' + NS + ';i=134',
   BoilerType_CustomController_Input2: 'nsu=' + NS + ';i=135',
   BoilerType_CustomController_Input3: 'nsu=' + NS + ';i=136',
   BoilerType_CustomController_ControlOut: 'nsu=' + NS + ';i=137',
   BoilerType_ChangeSetPoints_InputArguments: 'nsu=' + NS + ';i=201',
   BoilerType_ChangeSetPoints_OutputArguments: 'nsu=' + NS + ';i=202',
   BoilerType_EmergencyShutdown_InputArguments: 'nsu=' + NS + ';i=204',
   BoilerType_EmergencyShutdown_OutputArguments: 'nsu=' + NS + ';i=205',
   BoilerType_Restart_InputArguments: 'nsu=' + NS + ';i=207',
   BoilerType_Restart_OutputArguments: 'nsu=' + NS + ';i=208',
   Boiler1_InputPipe_FlowTransmitter1_Output: 'nsu=' + NS + ';i=141',
   Boiler1_InputPipe_FlowTransmitter1_Output_EURange: 'nsu=' + NS + ';i=144',
   Boiler1_InputPipe_FlowTransmitter1_Output_EngineeringUnits: 'nsu=' + NS + ';i=146',
   Boiler1_InputPipe_Valve_Input: 'nsu=' + NS + ';i=148',
   Boiler1_InputPipe_Valve_Input_EURange: 'nsu=' + NS + ';i=151',
   Boiler1_InputPipe_Valve_EnergyConsumption: 'nsu=' + NS + ';i=50',
   Boiler1_InputPipe_Valve_EnergyConsumption_EngineeringUnits: 'nsu=' + NS + ';i=240',
   Boiler1_Drum_LevelIndicator_Output: 'nsu=' + NS + ';i=156',
   Boiler1_Drum_LevelIndicator_Output_EURange: 'nsu=' + NS + ';i=159',
   Boiler1_Drum_LevelIndicator_Output_EngineeringUnits: 'nsu=' + NS + ';i=161',
   Boiler1_OutputPipe_FlowTransmitter2_Output: 'nsu=' + NS + ';i=164',
   Boiler1_OutputPipe_FlowTransmitter2_Output_EURange: 'nsu=' + NS + ';i=167',
   Boiler1_OutputPipe_FlowTransmitter2_Output_EngineeringUnits: 'nsu=' + NS + ';i=169',
   Boiler1_FlowController_Measurement: 'nsu=' + NS + ';i=171',
   Boiler1_FlowController_SetPoint: 'nsu=' + NS + ';i=172',
   Boiler1_FlowController_ControlOut: 'nsu=' + NS + ';i=173',
   Boiler1_LevelController_Measurement: 'nsu=' + NS + ';i=175',
   Boiler1_LevelController_SetPoint: 'nsu=' + NS + ';i=176',
   Boiler1_LevelController_ControlOut: 'nsu=' + NS + ';i=177',
   Boiler1_CustomController_Input1: 'nsu=' + NS + ';i=179',
   Boiler1_CustomController_Input2: 'nsu=' + NS + ';i=180',
   Boiler1_CustomController_Input3: 'nsu=' + NS + ';i=181',
   Boiler1_CustomController_ControlOut: 'nsu=' + NS + ';i=182',
   Boiler1_ChangeSetPoints_InputArguments: 'nsu=' + NS + ';i=210',
   Boiler1_ChangeSetPoints_OutputArguments: 'nsu=' + NS + ';i=211',
   Boiler1_EmergencyShutdown_InputArguments: 'nsu=' + NS + ';i=213',
   Boiler1_EmergencyShutdown_OutputArguments: 'nsu=' + NS + ';i=214',
   Boiler1_Restart_InputArguments: 'nsu=' + NS + ';i=216',
   Boiler1_Restart_OutputArguments: 'nsu=' + NS + ';i=217',
   Boiler_BinarySchema: 'nsu=' + NS + ';i=192',
   Boiler_BinarySchema_NamespaceUri: 'nsu=' + NS + ';i=194',
   Boiler_BinarySchema_Deprecated: 'nsu=' + NS + ';i=15001',
   Boiler_BinarySchema_EnergyConsumptionType: 'nsu=' + NS + ';i=242',
   Boiler_BinarySchema_ChangeSetPointsRequest: 'nsu=' + NS + ';i=224',
   Boiler_BinarySchema_ChangeSetPointsResponse: 'nsu=' + NS + ';i=227',
   Boiler_XmlSchema: 'nsu=' + NS + ';i=185',
   Boiler_XmlSchema_NamespaceUri: 'nsu=' + NS + ';i=187',
   Boiler_XmlSchema_Deprecated: 'nsu=' + NS + ';i=15002',
   Boiler_XmlSchema_EnergyConsumptionType: 'nsu=' + NS + ';i=246',
   Boiler_XmlSchema_ChangeSetPointsRequest: 'nsu=' + NS + ';i=232',
   Boiler_XmlSchema_ChangeSetPointsResponse: 'nsu=' + NS + ';i=235',
});
